### ISSUE TITLE
Encryption of personal data

### ISSUE THREAD

**Issue by ITfee** [mailpoet/mailpoet#1606]
GDPR demands to take measures on security when handling personal data. However MailPoet currently does not encrypt any data stored in database tables, so theoretically evil minded people could hack into it and grab e.g. email adresses and other personal data.
Therefore I would like to suggest a feature to better protect such data in MailPoet.

**Comment by pavel-mailpoet** [comment]
Hey, thanks for writing to us. We understand it is very important for you to be GDPR compliant.

Some sources note that encryption is optional under GDPR.
https://www.linkedin.com/pulse/gdpr-encryption-mandatory-gary-hibberd/ and https://gdpr-info.eu/art-32-gdpr/

The responsibility for encryption shouldn’t lay on the plugin makers. It should really be at the DB level, set up by the sysadmin, and not the WP plugin, where encryption keys are easily accessible for the attacker.
