### ISSUE TITLE
Highland Lakes HOA paid you $550.00 and the check cleared 7 days ago but we don’t have email for our newsletters or posts!

### ISSUE THREAD

**Issue by carasmo** [mailpoet/mailpoet#1737]
Highland Lakes HOA paid you $550.00 and the check cleared 7 days ago but we don’t have email for our newsletters or posts! This is horrible!

**Comment by flakas** [comment]
@carasmo sorry to hear you are experiencing issues, please contact our support team here: https://www.mailpoet.com/support/sales-pre-sales-questions/
Unfortunately we are not able to help you on this forum - this is a public repository for the codebase.

**Comment by flakas** [comment]
I understand you are looking forward to the service you have paid for, thank you for your patience.
If you have contacted our support team via the link above, our support team will respond within the next 24 hours.

**Comment by carasmo** [comment]
Yes, the Finance committee lead has emailed 5 times last week. Got the thank you for payment 7 days ago, and then emailed numerous times today. They are a premium subscriber and sent a payment for over a half a grand, so it's really unfortunate that the service is this poor.
