### ISSUE TITLE
Cannot save settings

### ISSUE THREAD

**Issue by gruntaway** [mailpoet/mailpoet#1983]
Hi,

When attempting to save settings, I just get a blank page.

The URL address contains a bunch of get query parameters, so it looks like it's not posting with post method properly.

I'm running a fresh installation of WordPress (latest version), including the latest version of Mailpoet.

Everything else works fine, it's just the settings which cannot be saved for some reason. I have already tried simply adding "method=post" to the <form> element, which fixes the "blank screen", but it still doesn't save the input values.

**Comment by gruntaway** [comment]
Additionally (this might be useful), I am getting a JS-error in the console only on the settings page. See attached screenshot.

![Screenshot 2019-04-18 at 12 30 24](https://user-images.githubusercontent.com/223618/56355140-db7f6b80-61d5-11e9-9531-d8db13ee73fe.png)

**Comment by NeosinneR** [comment]
Hey @gruntaway, thanks for the report. Can I ask what browser are you using?
