### ISSUE TITLE
Cannot send a mail, because 'mailpoet_newsletter_links' doesn't exist

### ISSUE THREAD

**Issue by MoOx** [mailpoet/mailpoet#2006]
Hi,

I recently installed your plugin & everything seems to work (at least form+subscription).
I tried to send a first newsletter but nothing has been sent.
After digging a little I found this issue:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mailpoet_newsletter_links' doesn't exist
```

(I removed my db name & prefix from the message, for privacy, but it was more like `SQLSTATE[42S02]: Base table or view not found: 1146 Table '{db_name}.{db_prefix}_mailpoet_newsletter_links' doesn't exist`

I checked my php log on found this

```
Erreur de la base de donnÃ©es WordPress Index column size too large. The maximum column size is 767 bytes. pour la requÃªte CREATE TABLE gdy_mailpoet_newsletter_links (
id int(11) unsigned NOT NULL AUTO_INCREMENT,
newsletter_id int(11) unsigned NOT NULL,
queue_id int(11) unsigned NOT NULL,
url varchar(2083) NOT NULL,
hash varchar(20) NOT NULL,
created_at timestamp NULL,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY  (id),
KEY newsletter_id (newsletter_id),
KEY queue_id (queue_id),
KEY url (url(255))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci faite par activate_plugin, do_action('activate_mailpoet/mailpoet.php'), WP_Hook->do_action, WP_Hook->apply_filters, MailPoet\Config\Initializer->runActivator, MailPoet\Config\Activator->activate, MailPoet\Config\Migrator->up, dbDelta
```

Note that my wordpress install is in french, that why there is some part of the error that are in french :)

I found this issue that seems related https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes

I am not confortable with mysql so I will wait for an answer instead of trying weird things :)

---

PHP 7.3
MySQL 5.5

**Comment by costasovo** [comment]
Hi MoOx,
thank you for reporting this issue. We are looking into it and will ship the fix in one of the upcoming releases.
