### ISSUE TITLE
conflict with theme causes form edit page not to load

### ISSUE THREAD

**Issue by ituk** [mailpoet/mailpoet#2013]
Hey,
When I try to create a new form or edit an existing one, the editing page loads without it’s content, only header and an empty block.
I use Pojo Scoop theme, so I switched to one the wp default themes, and the problem was solved. unfortunately the people at template support say the problem is with the plugin, and they refuse to help any further…
I’m using Mailpoet 3.
here is a screenshot of the problem, with error console open (these error don’t show up with the other theme):
https://snag.gy/4bYeoV.jpg
errors:
`Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined`
`TypeError: aa.dispatchEvent is not a function`

Thanks,
Itamar

**Comment by costasovo** [comment]
Hi Itamar,
thank you for reporting this conflict. We are looking into this issue.
