### ISSUE TITLE
http 500 error mailpoet v3.25 and wp v4.7.13

### ISSUE THREAD

**Issue by jozwa** [mailpoet/mailpoet#2021]
i updated mailpoet 3 to 3.25. after that my wordpress site generate a http 500 error on the front-end and back-end. after the update i open a ftp connection and renamed the mailpoet folder and therefor i disabled the plugin. The website work again.

**Comment by pavel-mailpoet** [comment]
Hello jozwa,

thank you for reporting this. We are aware of this problem in old WordPress versions. We fixed it in this commit: https://github.com/mailpoet/mailpoet/commit/388814d2263e5da9988c92f0821834f97a5180f1
