### ISSUE TITLE
[FEATURE REQUEST] Resend New post notification

### ISSUE THREAD

**Issue by wattan1** [mailpoet/mailpoet#2026]
I would really like to see an option to resend a notification after updating an old post. Many similar services offer this option, either by checking a box in the post editor or just sending out a notification on republication.

**Comment by qfrery** [comment]
Hi @wattan1,

Thanks for your request. I've taken note of it and I will let you know when it will be implemented.

For you to know, we are quite busy at the moment and it might take a while.

**Comment by wattan1** [comment]
Hi Quentin,

Thank you for the notification and I'm looking forward to it.

Best regards,

Martijn Vos

Op do 6 jun. 2019 15:47 schreef Quentin Frery <notifications@github.com>:
