### ISSUE TITLE
API docs use class_exists() incorrectly

### ISSUE THREAD

**Issue by deltafactory** [mailpoet/mailpoet#2123]
[On this page](https://github.com/mailpoet/mailpoet/blob/master/doc/UsageExamples.md) and elsewhere, the call to `class_exists()` appears incorrectly. The first argument should be a string and not reference a method.

`if (class_exists(\MailPoet\API\API::class)) {`

should be
`if (class_exists('\MailPoet\API\API')) {`

**Comment by JanJakes** [comment]
Hi @deltafactory, thanks for sharing your findings. However, `\MailPoet\API\API::class` is indeed a string, not a reference. In PHP `::class` works for any (including non-existent) classes and evaluates to the expected string. See https://3v4l.org/T9JBs. Thanks, Jan

**Comment by deltafactory** [comment]
My apologies, I wasn't aware of that feature.
