### ISSUE TITLE
Upgrading from 3.34.3 to 3.34.4 continually fails.

### ISSUE THREAD

**Issue by spam-n-eggs** [mailpoet/mailpoet#2201]
Upgrading from MailPoet 3.34.3 to 3.34.4 on WP 5.2.2 puts the site into maintenance mode, and then never completes, resulting in the need to manually remove the .maintenance file.

**Comment by pavel-mailpoet** [comment]
Sorry to hear you are experiencing issues, please contact our support team here: https://www.mailpoet.com/support/sales-pre-sales-questions/
Unfortunately, we are not able to help you on this forum - this is a public repository for the codebase.
