### ISSUE TITLE
[Feature Request] MailPoet Hook to get content from External API

### ISSUE THREAD

**Issue by mesodiar** [mailpoet/mailpoet#2293]
According to **generateExcerpt**  in https://github.com/mailpoet/mailpoet/blob/54ae6362dc46c1f9a13bd534fb5bfd8838d2c156/lib/Newsletter/Editor/PostContentManager.php#L80.

Is there any possible hook or anyway that I can generate the excerpt from post content that comes from external API?

My restriction is I don't want to add the post_content or excerpt in each post.

**Comment by flakas** [comment]
Hey @mesodiar,

Thanks for the feature request, but unfortunately this is not something we intend add support for within MailPoet in near future.

However, I can share a lead that might help you find a way to do so.
Under the hood MailPoet 3 uses `get_posts()` to [fetch the correct posts](https://github.com/mailpoet/mailpoet/blob/54ae6362dc46c1f9a13bd534fb5bfd8838d2c156/lib/Newsletter/AutomatedLatestContent.php#L99) for inclusion in emails.
If you are able to modify what `get_posts()` in such a way that the excerpt you need is already generated (e.g. by loading the excerpt from an external API) - MailPoet should be able to use the supplied excerpt.

We haven't tested it, so I'm not sure if it will really work, but you may be able to use `the_posts` filter to fetch and inject the excerpts into a list of posts:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L3159

I hope that helps.
