### ISSUE TITLE
Feature Request: Allow tuning of CronHelper DAEMON_EXECUTION_LIMIT

### ISSUE THREAD

**Issue by deltafactory** [mailpoet/mailpoet#2319]
The current execution time limit is set to 20 seconds. Bulk sending operations that operate efficiently are only allowed to use 1/3rd of the available minute - and is worse for longer intervals. In my scenario, that effectively limits my send rate.

Please allow some additional control over these limits, either as a constant or filter. Implementing as a filter could allow some contextually relevant behavior for specific cron tasks.

**Comment by flakas** [comment]
Hey @deltafactory,

Thanks for the feature suggestion.
We've added this to our work queue, adding a WordPress filter to control the cron execution limit.
Unfortunately, I can't provide a more precise timeline than that.

**Comment by flakas** [comment]
Hey @deltafactory, the filters have been implemented in #2345 and should be released with the next release on 2019-10-01.
Thanks for the suggestion!
