### ISSUE TITLE
Feature Request: Support for wpdb customizations - HyperDB, multi-server environments

### ISSUE THREAD

**Issue by deltafactory** [mailpoet/mailpoet#2320]
To my recollection, MailPoet's database abstraction does not use $wpdb but instead connects via PDO after pulling the connection information from the $wpdb global.

As implemented, this causes incorrect behavior in certain configurations. For example, master/slave environments using read replica(s) or partitioned tables.

What options are available, or can be made available to support these types of configurations or otherwise customize MailPoet's database connection? Are there any plans to bring the current implementation in line with $wpdb (inherently addressing this issue)?

**Comment by costasovo** [comment]
Hi @deltafactory,
The plugin currently doesn't support read replicas. MailPoet uses configuration from settings constants defined within wp-confing.php (see [here](https://github.com/mailpoet/mailpoet/blob/master/mailpoet_initializer.php#L59)). 
When you pass configuration for master into those it should work correctly.

We had some discussions about using $wpdb and we want to investigate this idea further, but so far there isn't any schedule for that.
