### ISSUE TITLE
Feature Request: Allow higher send rates for people who know what they're doing

### ISSUE THREAD

**Issue by deltafactory** [mailpoet/mailpoet#2329]
I consider this a bug because it's enforced in code. The solution could also be implemented in code.

Wanting 1000 emails per minute may be an edge case but it's a real one. (5000/min, < 0.2% bounce rate.) Our capabilities exceed that and are artificially throttled by the parameter in the "Send With..." settings page and DAEMON_EXECUTION_LIMIT (see #2319.)

I understand the reason behind it and the copious warnings but suggest that the solution may be to raise the barrier of entry by allow raising of limits through code.

**Comment by NeosinneR** [comment]
Hey @deltafactory,

thanks for the suggestion, but I'm afraid we don't have it on our priorities list. We have a feature requests board at https://feedback.mailpoet.com/ so if you want, you can add the request there.
