### ISSUE TITLE
Bounce (return-path) email not set

### ISSUE THREAD

**Issue by loxK** [mailpoet/mailpoet#2356]
I use latest mailpoet with SMTP sending. If I set a bounce email address, it is not set in emails sent.

Looking at the code I do not see the `return-path` set anywhere nor the `settings[bounce_email] `setting used.

**Comment by pavel-mailpoet** [comment]
Hello @loxK ,
thank you for the report. We will fix that problem and notify you when it is fixed.

**Comment by pavel-mailpoet** [comment]
@loxK ,

I teste it again and it seems that everything works as expected. The settings value is grabbed here: https://github.com/mailpoet/mailpoet/blob/master/lib/Mailer/Mailer.php#L161

It is passed to SMTP here: https://github.com/mailpoet/mailpoet/blob/master/lib/Mailer/Methods/SMTP.php#L107
