### ISSUE TITLE
Multisite switch_to_blog does not return queried blog lists

### ISSUE THREAD

**Issue by aurovrata** [mailpoet/mailpoet#2406]
I am trying to access and manipulate a mailpoet list on a multisite installation.

Child sites have subscription forms which all subscribe to the same list which exists on the main site (blog_id=1),

`
switch_to_blog(1);
    debug_msg('switch to blog 1');
    if (class_exists(\MailPoet\API\API::class)) {
      $mailpoet_api = \MailPoet\API\API::MP('v1');
      $mp_lists = $mailpoet_api->getLists();
      foreach($mp_lists as $list){
        if(!empty($list['deleted_at'])) continue; //list is in trash.
        $lists[$list['id']]=$list['name'];
      }
    }
    restore_current_blog();
`
but this does not work.  Loking at the code I reckon the lists are stored in memory instead of being picked up from DB, and hence does not pick up the data as per the blog being queried.

I believe this is a bug, as this would be the expected functionality on a multisite installation.

**Comment by aurovrata** [comment]
ok, even on premium licenses?

**Comment by pavel-mailpoet** [comment]
no, not even on premium licenses: https://www.mailpoet.com/blog/multisite-newsletter/

**Comment by aurovrata** [comment]
thanks for the link, it's a partial solution for multisites, but its not the solution we are seeking.

**Comment by aurovrata** [comment]
For anyone reading this thread, I finally settled for a custom REST route which allows me to add new subscribers to a list  as well as search available lists.

Here is the code I used to add a simple subscription REST api interface,
`
/**
* register rest api route for mailpoet subscription.
* hooked on 'rest_api_init'.
*@since 2.3.0
*/
public function mailpoet_wpjson_subscription(){
  register_rest_route( 'mailpoet', '/subscribe', array(
    array(
        'methods'  => WP_REST_Server::READABLE,
        'callback' => array($this, 'new_mailpoet_subscription') ,
      )
    ));
}
//simple subscription using only the email.
public function new_mailpoet_subscription($request){
  $params = $request->get_params();
  $return = array('subscribed' => false);
  if(isset($params['email']) && isset($params['list'])){
    if(isset($params['nonce']) && wp_verify_nonce($params['nonce'], 'mailp-subscribe-nonce')){
      if (class_exists(\MailPoet\API\API::class)) {
        $mailpoet_api = \MailPoet\API\API::MP('v1');
        try{
          $result = $mailpoet_api->addSubscriber(array('email'=>$params['email']), array($params['list']));
          $return['subscribed']=true;
          $return['response']='Subscription successful, a confirmation mail will be sent.';
        } catch (\Exception $e) {
          $return['error'] = $e->getMessage();
        }
      }
    }else $return['error']='Invalid request, try again.';
  }
  return $return;
}
`
browsing to:
`http://localhost/wordpress/wp-json/mailpoet/subscribe?email=test@example.com&list=3`
will trigger the script.
