### ISSUE TITLE
[newsletter:total] shows one too much

### ISSUE THREAD

**Issue by ibes** [mailpoet/mailpoet#2407]
Hi there,

for my installation, the shortcode [newsletter:total] -  which I expect to show the total number of elements in this post notification mail - shows always 1 more than there really are. 

How could that be?
Is this a bug or have I configurated something wrong or ...?

Sebastian

**Comment by pavel-mailpoet** [comment]
Sorry to hear you are experiencing issues, please contact our support team here: https://www.mailpoet.com/support/sales-pre-sales-questions/

Unfortunately, we are not able to help you on this forum - this is a public repository for the codebase.
