### ISSUE TITLE
Newsletter Management Display should have filters

### ISSUE THREAD

**Issue by ibes** [mailpoet/mailpoet#2412]
Hi there,

this function displays the newsletter management panel. https://github.com/mailpoet/mailpoet/blob/8b723ce5ed4b41aaf4dd4f94c9d4b4f752600634/lib/Subscription/Pages.php#L296

We want to have things more slick and I will likely have to change things with CSS and JS. 
It would be so great to have a chance to change
a) the template / markup
b) the fileds. 

There could be a filter for the fields that will be displayed. 
And the whole form should in the best case use a template that can be overwritten. 

The HTML that is generated for the form is quite bad. Inline CSS, no classes, stars for required fields that can't be targeted with CSS (could be an ":after" rule or at least a <span class="required-field-indicator"> or so). 

Are there plans to make this more customizable?!

I am surprised that MailPoet is such a mature service but the level of easy customizability feels quite low.

**Comment by pavel-mailpoet** [comment]
Hi @ibes 
I agree with you, the page is a mess. I created a ticket in the internal tracking system and we will target those problems. We will let you know when it is released.

**Comment by wxa** [comment]
@ibes MailPoet 3.48.0 was released today, it contains new filters, `mailpoet_manage_subscription_page_form_fields` and `mailpoet_manage_subscription_page`, which allow you to customize the Manage Subscription page fields and template.
