### ISSUE TITLE
Update nesbot/Carbon to version 2

### ISSUE THREAD

**Issue by makakken** [mailpoet/mailpoet#2478]
i have a written an calendar-plugin for one of my customers, using nesbot/carbon v2. when activating mailpoet, everything crashes, because I use isoFormat-function ov Carbon, which is not included in V1, but the template file loads your carbon/v1 instead of mine carbon/v2 (which works pretty fine in the admin panel, but not on the frontend). Because they share namespaces, it's not possible for me to exactly determine which carbon library is loaded. Do you have any suggestions for fixing that? is there any reason you're still using carbon v1?

**Comment by pavel-mailpoet** [comment]
Hello makakken,

there is a reason we are still using carbon v1 and that is the PHP support. Our plugin still supports PHP 5.6. There is a solution to this problem, however. We have two vendor folders. `vendor` has libraries from composer and `vendor-prefixed` contains libraries that were moved into our own namespace. We haven't moved Carbon yet. But I will add the task to our Jira and we will move Carbon as well.
