### ISSUE TITLE
Google font not included correctly

### ISSUE THREAD

**Issue by bago** [mailpoet/mailpoet#2479]
StylesHelper.php includes Google Font in an html comment:

`<!--[if !mso]><link href="https://fonts.googleapis.com/css?family=####" rel="stylesheet"><![endif]-->`

Sounds like a conditional comment that will be interpreted as html code only from internet explorer.

I guess you wanted to add the Google Font but prevent it from showing up in Outlook (as it breaks things), but the right conditional comments syntax is:

```
<!--[if !mso]><!-- -->
<link href="https://fonts.googleapis.com/css?family=XXXX" rel="stylesheet" />
<!--<![endif]-->
```

**Comment by pavel-mailpoet** [comment]
Thank you bago for the report, we will look into it.

**Comment by bago** [comment]
Sounds like you implemented it right at first, but then broken it in this refactoring:
https://github.com/mailpoet/mailpoet/commit/62e47dcf12de3506922389d8d4e3af16424f7f46

**Comment by JanJakes** [comment]
Fixed by https://github.com/mailpoet/mailpoet/pull/2494.
