### ISSUE TITLE
Shoudn't gmail oauth be supported?

### ISSUE THREAD

**Issue by beppe9000** [mailpoet/mailpoet#2518]

**Comment by pavel-mailpoet** [comment]
@beppe9000 could you provide more details about what exactly are you expecting to be supported. But please do that using the customer support link in the plugin or here: https://www.mailpoet.com/support/sales-pre-sales-questions/

Unfortunately, we are not able to help you on this forum - this is a public repository for the codebase.

**Comment by beppe9000** [comment]
see [this](https://developers.google.com/gmail/imap/imap-smtp) for what I mean

**Comment by pavel-mailpoet** [comment]
I see, but I am afraid there is not a big demand for that so I cannot promise anything.

**Comment by beppe9000** [comment]
No problem, I had already used some workarounds. 😄
