### ISSUE TITLE
Duplicate e-mails multiple categories

### ISSUE THREAD

**Issue by wattan1** [mailpoet/mailpoet#2595]
I have one list per category so the subscribers can subscribe to a specific category. Of course people can subscribe to more than one category or tag. 

Now, if there is an overlap in the post so it has in multiple categories or tags and they are subscribed to both categories (so voth lists), they get a duplicate e-mail. Shouldn't there be a way so that people can't receive the same post twice even if they are in different lists? 

This is a huge problem for me.

**Comment by pavel-mailpoet** [comment]
Hello, 
wattan1. MailPoet doesn't send duplicate emails. You can read about it here: https://kb.mailpoet.com/article/298-can-subscribers-on-multiple-lists-get-duplicate-emails

Please contact the customer support from the plugin if you are still having this issue

**Comment by wattan1** [comment]
Hi Pavel,

Maybe you didn't understand my post, but it defintely does in the situation described above. I have been in contact with support about this issue multiple times and they have confirmed it, but it has no priority. You can find the confirmation on forums too. Examples:

https://wordpress.org/support/topic/duplicated-post-notifications-with-multiple-sign-up-categories/

https://wordpress.org/support/topic/good-plugin-but-with-a-few-issues/

**Comment by pavel-mailpoet** [comment]
Right, I understand now what you are referring to. We have been talking about it and we are aware of this problem. We need to decide how to resolve it. I am afraid I cannot give you any ETA on this.

**Comment by wattan1** [comment]
Okay. Thanks for the response. I opened a new issue because I didn't know if a closed issue would be seen.

**Comment by pavel-mailpoet** [comment]
Yes, they are seen, we are getting notifications. Please don't open more issues about it.
