### ISSUE TITLE
API missing functionalities 

### ISSUE THREAD

**Issue by gfirem** [mailpoet/mailpoet#2627]
Hello,
I'm part of the Themekraft team, we are working to create an extension to let our clients work with MailPoet. I'm facing an issue with the API you recommend to work with https://github.com/mailpoet/mailpoet/tree/master/doc. 

Base on the documentation is recommended to interact with mailpoet trough the API v1, but some functionalities are not present in the API. 
Some missing functionalities I need for my uses cases are: 
- Update the subscriber fields.
- Delete a subscriber.

I manage to solve it using the `Subscriber` class but it is not the recommendation. 

Did you have plans to improve the API? Have an ETA? 

@codemonkey-jack

**Comment by pavel-mailpoet** [comment]
Hello,

please don't use `Subscriber` class. We are doing some refactors and that class is very going to be removed. 

I created a tasks for your API improvement requests in our internal JIRA, but I am afraid there is no ETA. 

Pavel

**Comment by gfirem** [comment]
What other option. I have if I need to update subscriber fields?

**Comment by pavel-mailpoet** [comment]
What is the use-case? What subscriber fields do you need to update?

**Comment by gfirem** [comment]
I have a **dynamic** form where one user can define which fields match with MailPoet, the fields in mailpoet can be the default or custom. The idea is each time the user submits the form the field gets updated.

**Comment by gfirem** [comment]
Also, another use-case is If a user is deleted or we need to delete it when a form is submitted.

**Comment by pavel-mailpoet** [comment]
I am afraid we don't support such use-case at the moment. But using the class `Subscriber` is not a very safe option and will lead to problems for your clients.

**Comment by gfirem** [comment]
Then the only way to update user custom fields is when the subscriber is created

**Comment by gfirem** [comment]
Exist a safe way I can delete a subscriber?

**Comment by gfirem** [comment]
Exist a way I can be aware when `Subscriber` class changes? Or I can provide help to improve the API adding a method to get the subscriber instance. Like next.

```
  public function getSubscriberInstance($subscriberEmail) {
    $subscriber = Subscriber::findOne($subscriberEmail);
    // throw exception when subscriber does not exist
    if (!$subscriber) {
      throw new APIException(__('This subscriber does not exist.', 'mailpoet'), APIException::SUBSCRIBER_NOT_EXISTS);
    }
    return $subscriber;
  }
```

**Comment by pavel-mailpoet** [comment]
> Then the only way to update user custom fields is when the subscriber is created

That is correct.

> Exist a safe way I can delete a subscriber?

Not using the API.

> I can provide help to improve the API adding a method to get the subscriber instance

Well, your code doesn't help much. We don't want to leak our internal classes outside of our plugin. This is doing exactly that. We are moving from the old ORM to Doctrine so when we refactor the `Subscriber` class we will replace it with something completely different with a different interface.

**Comment by gfirem** [comment]
Amazing @pavel-mailpoet thanks a lot for all the information. 

I have 2 options: 
- Not release our Sync functionality until the new version is available. 
- Use the `Subscriber` class where I manage to all work. 

Do you have a beta program where you have internal releases where we can test our integration before new mailpoet gets released?

**Comment by pavel-mailpoet** [comment]
Sorry, we don't have any beta program for the internal releases.

**Comment by gfirem** [comment]
Ok, thanks a lot.
