### ISSUE TITLE
New integration

### ISSUE THREAD

**Issue by gfirem** [mailpoet/mailpoet#2647]
Hello, we build one plugin to integrate BuddyForms with MailPoet.

 https://themekraft.com/buddyforms/

https://github.com/BuddyForms/buddyforms-mailpoet

@pavel-mailpoet 
@codemonkey-jack

**Comment by JanJakes** [comment]
Hi @gfirem, thanks for letting us now. I checked the code and it seems you're good - accessing MailPoet through the API classes, which is the correct way of implementing an integration. We'll add your plugin to the list of integrations on our website: https://www.mailpoet.com/plugins/

**Comment by gfirem** [comment]
Thanks @JanJakes this is the page of the landing

https://themekraft.com/products/buddyforms-mailpoet/

**Comment by JanJakes** [comment]
@gfirem Thanks! I'd like to ask you for two small things:

1. Our logo design has changed a bit, see https://www.mailpoet.com/logo. Could you please update that?
2. We would love a link back to https://www.mailpoet.com/, for SEO purposes.

Thanks!

**Comment by gfirem** [comment]
@JanJakes I'm not clear about the issue with the logo on our landing. The problems are because we are using the white version over the orange, or the issue is the gradient behind?

**Comment by JanJakes** [comment]
@gfirem It's the shape, it has changed a bit. Colors should be fine.

Btw. we've already added you, see https://www.mailpoet.com/plugins/ 😉

**Comment by idocenko** [comment]
@gfirem you use absolutely different (maybe own) logo. For example, 'M' is cut and 't' is absolutely different. @JanJakes wrote you the link with a correct logo example.

**Comment by gfirem** [comment]
Thanks, @idocenko I notice the error and update all of our images. 

Also, I added a link in our landing to your site and I will write to our community with a link to the appsumo deal https://appsumo.com/mailpoet/
