### ISSUE TITLE
Memory usage when building sending queue for large dynamic segments

### ISSUE THREAD

**Issue by deltafactory** [mailpoet/mailpoet#2650]
When sending a message to a dynamic segment based on WP user roles, querying approx 170K users, PHP errored out when it reached the configured 512MB memory limit. We were able to complete the task by raising the WP memory limit to 2GB.

I haven't looked at the specifics but I'm assuming memory usage could be reduced with optimizations to query data, or batched queries.

**Comment by NeosinneR** [comment]
Hey @deltafactory,

thanks for the report. I created a ticket in our internal system, but I have no ETA as for when we'll get to this, so I'm closing this ticket.
