### ISSUE TITLE
Delete Email Hook

### ISSUE THREAD

**Issue by not-enough-yet** [mailpoet/mailpoet#2674]
We are working on a plugin that we hope to support users using MailPoet. Are there any hooks that allow us to hook in after and before an email is completely deleted?

We need it to behave similarly to [delete_post](https://developer.wordpress.org/reference/hooks/delete_post/) and [after_delete_post](after_delete_post).

Thanks in advanced.

**Comment by costasovo** [comment]
Hi @not-enough-yet ,
thanks for contacting us. We don't have hooks for that. You can find a list of supported actions [here](https://kb.mailpoet.com/article/274-list-of-filters-and-actions).

I've added a task for creating those hooks into our internal system. Unfortunately, I am not able to give you ETA for this change.

**Comment by not-enough-yet** [comment]
Thanks for the response @costasovo. I did look through that list prior to my post. As this is very important to us, is it possible for myself to be notified when there is an idea of an ETA? Anything would be helpful.

Thank you.

**Comment by NeosinneR** [comment]
@not-enough-yet I'm closing this issue. I added a note to the ticket in our internal system to notify you when we start working on this. But right now, there is no near-future plan to start working on it.
