### ISSUE TITLE
The ease of static analysis!

### ISSUE THREAD

**Issue by szepeviktor** [mailpoet/mailpoet#2696]
Hello! You do not need WordPress installed to run @phpstan.
[Static analysis](https://github.com/mailpoet/mailpoet/tree/master/tasks/phpstan) is meant to be ran on the source code only.

Use the unofficial [WordPress extension](https://packagist.org/packages/szepeviktor/phpstan-wordpress)!
Feel free to ask questions ❤️

**Comment by pavel-mailpoet** [comment]
Thank you @szepeviktor for the information. We will definitely give this a try. I added this information to our internal issue tracker and I am closing this.

**Comment by szepeviktor** [comment]
Thank you.

> internal issue tracker

Please consider working transparently as for example the Yoast team does.
