### ISSUE TITLE
New subscriber notification is sent twice

### ISSUE THREAD

**Issue by ericnicolaas** [mailpoet/mailpoet#2719]
I [posted](https://wordpress.org/support/topic/new-subscriber-email-sent-twice/) about this issue on the wp.org support forum earlier, but after digging into it some more I'm fairly confident this is a bug in the `MailPoet\API\MP\v1\API::addSubscriber()` method. Here is the problematic code:

```
    if (!empty($listIds)) {
      $this->subscribeToLists($newSubscriber->id, $listIds, [
        'send_confirmation_email' => $sendConfirmationEmail,
        'schedule_welcome_email' => $scheduleWelcomeEmail,
        'skip_subscriber_notification' => $skipSubscriberNotification,
      ]);

      // schedule welcome email(s)
      if ($scheduleWelcomeEmail && $newSubscriber->status === Subscriber::STATUS_SUBSCRIBED) {
        $this->_scheduleWelcomeNotification($newSubscriber, $listIds);
      }

      if (!$skipSubscriberNotification && ($newSubscriber->status === Subscriber::STATUS_SUBSCRIBED)) {
        $this->sendSubscriberNotification($newSubscriber, $listIds);
      }
    }
```

From: https://github.com/mailpoet/mailpoet/blob/master/lib/API/MP/v1/API.php#L300-L315

The problem is that if `$listIds` is not empty, the `subscribeToLists()` method is called and it in turn calls the `sendSubscriberNotification()` method. This same method is also called further down. 

This is with the Signup Confirmation turned off.

To troubleshoot, I put `error_log( __METHOD__ )` into the `sendSubscriberNotification()` method itself, as well as the two spots where it is called. The result:

```
[14-Apr-2020 06:35:02 UTC] MailPoet\API\MP\v1\API::subscribeToLists
[14-Apr-2020 06:35:02 UTC] MailPoet\API\MP\v1\API::sendSubscriberNotification
[14-Apr-2020 06:35:02 UTC] MailPoet\API\MP\v1\API::addSubscriber
[14-Apr-2020 06:35:02 UTC] MailPoet\API\MP\v1\API::sendSubscriberNotification
```

**Comment by NeosinneR** [comment]
Hi @ericnicolaas,

thanks for the report! It indeed looks like a bug in our code. We'll notify you once the fix is released.

**Comment by costasovo** [comment]
Hi @ericnicolaas,
we've just released a fix for this issue. Please upgrade to 3.46.13.
