### ISSUE TITLE
styling/layout of confirmation mail (double opt in)

### ISSUE THREAD

**Issue by sissibieber** [mailpoet/mailpoet#2746]
I was wondering, since MailPoet is all about customization and templates for sending emails, why is there no possibility to style or adjust the layout for the signup confirmation email?

**Comment by flakas** [comment]
Hello @sissibieber,

Thank you for your question.
Could you please reach out to our support team via our [support page](https://www.mailpoet.com/support)?
They will be better set up to help your case. Thanks!

Unfortunately, on Github we cannot help with product usage based questions.
