### ISSUE TITLE
more conditions for woocommerce events (abandoned shopping cart only if in custom list)

### ISSUE THREAD

**Issue by sissibieber** [mailpoet/mailpoet#2747]
hello,

in order to comply with gdpr I added a custom list (called personalized marketing emails). So I want to send the abandoned shopping cart email only to those who are in the custom list I created before (and if they are subscribed).

any ideas on that?

**Comment by flakas** [comment]
Hello @sissibieber,

Thank you for your question.
Could you please reach out to our support team via our [support page](https://www.mailpoet.com/support)?
They will be better set up to help your case.

Thanks!
