### ISSUE TITLE
API addSubscriber status alredy unconfirmed

### ISSUE THREAD

**Issue by kepon85** [mailpoet/mailpoet#2835]
**Describe the bug**
I want to synchronize the members of my association in mailpoet to send them news. I looked with the API https://github.com/mailpoet/mailpoet/blob/master/doc/api_methods/AddSubscriber.md but even with send_confirmation_email at false and schedule_welcome_email at false or true the status returned is always unconfirmed ( when it should be confirmed according to the doc if the email is not sent ...

**my code**

```
<?php

// On charge wordpress
require_once('./wp-load.php');

// Mailpoet
$config['id_list']=6;

if (class_exists(\MailPoet\API\API::class)) {
	// Get MailPoet API instance
	$mailpoet_api = \MailPoet\API\API::MP('v1');
	// Get available list so that a subscriber can choose in which to subscribe 
	$subscriber['email']='david@myperssonalemail.fr';
	$list_ids=array($config['id_list']);
	$options['send_confirmation_email']=false;
	$options['schedule_welcome_email']=false;
	$options['skip_subscriber_notification']=true;
	$addSubscriber = $mailpoet_api->addSubscriber($subscriber, $list_ids, $options);
	var_dump($addSubscriber);
} else {
	echo "Error to load the class";
	exit();
}
?>
```

**Versions (please complete the following information):**
- WordPress version: 5.4 
- PHP version: 7.3
- MailPoet version: 3.46.11

Thank's for your help

David

**Comment by kepon85** [comment]
I fixed the problem with a mysql query but it is not very clean ...

```
try {
	$pdo = new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8', DB_USER, DB_PASSWORD);
} catch (PDOException $exception) {
	die($exception->getMessage());
}
$response = $pdo->query('UPDATE wp_mailpoet_subscribers set status="subscribed"  
						WHERE id in (
							SELECT subscriber_id 
							FROM wp_mailpoet_subscriber_segment 
							WHERE segment_id = '.$config['id_mailpoet_list'].'
						)');
```

**Comment by JanJakes** [comment]
Hi @kepon85, are you using the MailPoet Sending Service? Unfortunately, we don't support adding subscribers as "subscribed" when MailPoet Sending Service is used. In that case confirmation emails are required.

**Comment by kepon85** [comment]
> Hi @kepon85, are you using the MailPoet Sending Service? 

No

> Unfortunately, we don't support adding subscribers as "subscribed" when MailPoet Sending Service is used. In that case confirmation emails are required.

ok, I understand
Thank you !
