### ISSUE TITLE
Mailpoet Cron Calls

### ISSUE THREAD

**Issue by Sven74Muc** [mailpoet/mailpoet#2898]
I have installed a great plugin called Snitch. This plugin shows me that mailpoet generates every 15-20 seconds a cron server call like shown in the screenshoot. Meanwhile I have 3900 calls of this within 21 hours. this is true "server spam".

https://dlgo.de/mp-calls.jpg

Two questions:

1. For what are this calls needed?
2. Any chance to set the timing to a much longer time like 120 or 300 seconds?

I could assume that this calls are needed for post notifications. If this is the only reason, I could live with 1500 seconds.
I could live to adjust the timing manually through edding php, js,… files and repeat this after each plugin update.

This is the code in the functions.php:

```
554  public function wpRemotePost($url, array $args = []) {
555    return wp_remote_post($url, $args);
556  }

```

As of the fact that this is realy spamming the server, there is a quick fix needed. The number of calls are the one issue, the other is that this calls take 5 seconds which is very long.

**Comment by costasovo** [comment]
Hi @Sven74Muc,

these calls are done by MailPoets tasks scheduler. It is a background process which is responsible for sending newsletters and other background tasks which plugin does.

You can configure it to run via Linux cron. See our [knowledge base article on the topic](https://kb.mailpoet.com/article/129-what-is-the-newsletter-task-scheduler).

With default settings, it uses web request to trigger the process and the trigger request takes 5 seconds.

**Comment by costasovo** [comment]
@Sven74Muc If you experience some issues with the background process you can contact our support: https://www.mailpoet.com/support

**Comment by Sven74Muc** [comment]
Thanks costasovo.

There are still reasons for many user to use the MailPoet tast scheduler... but every 15 seconds or so if faar to much. I think it would be usefull to set the default time to 1 minute and the possibility to change this in the setting.
