### ISSUE TITLE
proposal for new post notification for private posts

### ISSUE THREAD

**Issue by stdbull** [mailpoet/mailpoet#2904]
**Describe the bug**
As documented in the Mailpoet 3 docs page:

> 8. Will protected or private posts show in the Post Notification?
> 
>No. Only publicly available posts will show in the post notification which means if you are protecting posts using a user role manager plugin, a membership plugin or the built-in WordPress post status of "private" the post will not show.

I understand this implementation and the reasons for. However, if on a site, a site admin wishes to have a 'private' distribution list of which only includes registered users (ie users who have a WP login to the site), it is reasonable to expect that the site admin may wish to allow posts which only those users are able to access, be notified to them in an email.

If there was a private WP category that only logged in users could view posts in, I don't see a reason to prevent Mailpoet from being able to notify registered users about such new posts in this category. Notifications to registered users who are permitted to view posts in that category should be able to be sent. The behaviour that exists today removes such control from the admin of the site and enforces behaviour which ought to be in the hands of the site admin. I think Mailpoet sees the request for subscription as an open request and because it doesn't support private lists, it assumes that any post not public is not in scope for notification. I think this is a limitation that would be nice to remove.

**To reproduce**
1. Install Wordpress Access Control (WPAC) and ensure there is a user who's role is Subscriber
2. Set up a Mailpoet New Posts Notification to a list, of which contains the registered user in 1
3. Author a new post in the category above and set WPAC access settings to Subscriber for that post
4. Publish the post

**Actual behaviour**
No New Post Notification email will be sent to the user specified in 1

**Expected behaviour**
This is the expected behaviour :-) But I'm hoping it can be changed / discussed :-)

**Versions (please complete the following information):**
- WordPress version: 5.2.2
- PHP version: 7.2.27
- Platform: self hosted FreeBSD 11
- MailPoet version: Free 3.47.6

**Proposal**
My suggestion is to make a pre sending hook available which passes the list of recipients and the filter used in the 'Automatic New Posts' widget, and in the theme the developer or admin could decide to accept or reject. if accept, the mail gets sent. If reject, no mail gets sent.

What do you think?

**Additional Context**
I have a WP site on a self hosted web server. I have a photoblog on there. On the site, users can login and when logged in, they can see photos that aren't visible when not logged in, for example family photos. When I publish a new photo in the private category, I would like to be able to send emails to registered users (family) with an embedded featured image in the email. This doesn't work today for the reasons above.

Without this limitation, Mailpoet works absolutely fine :-) so thanks for developing the plugin.

Cheers,
--  Matt

**Comment by wxa** [comment]
Hi Matt,

Thank you for writing to us! We understand your proposition and will discuss it within our team notifying you about the outcome.

**Comment by wxa** [comment]
@stdbull You can post your proposal on https://feedback.mailpoet.com/ and if enough users vote for it, we'll consider implementing it.
