### ISSUE TITLE
Confirmation url issue

### ISSUE THREAD

**Issue by JosigBarcos** [mailpoet/mailpoet#2918]
**Describe the bug**
When I use my own page to confirm the mail, the url does not include the parameter "mailpoet_page = subscriptions" and when a subscriber clicks on the confirm link, the status does not change to subscribed

I tried adding the parameter "mailpoet_page = subscriptions" to the link, then it worked perfectly, the status changed to subscribed with my own confirmation page

**To reproduce**
Just set up a different confirmation page than mailpoet, subscribe your email, and click the confirmation link. You will notice how the subscriber status does not change to subscribed.

But adding the parameter "mailpoet_page=subscriptions" to the confirmation link does work.

**Actual behavior**
Subscriber status does not change when confirmation link opens.

**Expected behavior**
User status changes to subscribed when confirmation link opens.

**Versions (please complete the following information):**
- WordPress version: 5.4.2
- PHP version: 7.3.19
- MailPoet version: 3.47.7 & 3.0.87 (premium)

**Additional context**

**Comment by wxa** [comment]
Hello @JosigBarcos,

I could not reproduce the issue you've described. The `mailpoet_page=subscriptions` parameter doesn't really matter when confirming a subscription, it's an address of the page to show after a subscriber is confirmed. In my tests confirmation worked with and without this bit, both on custom and on default pages.

There must be something else going on. Do you have page caching on your website? This may be the source of the problem. 

Could you please reach out to our support team via our [support page](https://www.mailpoet.com/support)? They will be better set up to help your case.
