### ISSUE TITLE
Cannot change the number of subscribers in the listings [MAILPOET-3045]

### ISSUE THREAD

**Issue by NeosinneR** [mailpoet/mailpoet#2958]
See the screenshot, changing the number has no effect. 

1. Ensure that the number of items to display is saved for the next visit - this should be maintained by WordPress, just make sure it really works.

2. When fixing this, please check also other listings pages in the plugin. Every listing should have its own number of items per page.

![Screen Shot 2020-07-07 at 12 40 27](https://user-images.githubusercontent.com/470616/89157631-1f35ea00-d56d-11ea-89f7-1a1fd2910f87.png)

**Comment by lysyjan** [comment]
This is WP issue: https://core.trac.wordpress.org/ticket/50392
