### ISSUE TITLE
HTML is not working at subscribe in comments

### ISSUE THREAD

**Issue by wassereimer86** [mailpoet/mailpoet#2998]
**Describe the bug**
HTML is not working at subscribe in comments.

**To reproduce**
1. Put a HTML link in the box where you can setup the displayed text
2. Click on save
3. Go in incognito tab to comments section. HTML is printed as text and not as a link

**Actual behavior**
HTML is not working at subscribe in comments.

**Expected behavior**
HTML should work at subscribe in comments for gdpr and to link to the data protection site.

**Versions (please complete the following information):**
- WordPress version: 5.5
- PHP version: 7.4.9
- MailPoet version: 3.48.1

**Comment by costasovo** [comment]
Hi @wassereimer86,
could you please post this to https://feedback.mailpoet.com/ ?

**Comment by wassereimer86** [comment]
No. I made a bug report here. And i don´t want to register on the site to post it there. You should make it easy for people to report things. Why are you here one Github if you point me to the other side?

**Comment by NeosinneR** [comment]
Hi @wassereimer86, I understand the frustration of having to register somewhere else, but from our point of view, this is not a bug (or something code related) but a feature request. And for those, we have dedicated service so other users can also see and vote for their favorite (which helps us make decisions). We don't have the capacity to keep tracking feature requests in many different services, therefore we decided to direct all users to https://feedback.mailpoet.com/.
