### ISSUE TITLE
Missing column "t0.status" in "field list" creates Fatal Exception in 3.49

### ISSUE THREAD

**Issue by fridde** [mailpoet/mailpoet#3008]
**Describe the bug**
After an update of Mail Poet 3 (New) to 3.49.0 I was met with the PDO exception below. I haven’t touched the database, so I wonder what could possibly have happened?

```php
Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught PDOException: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.status' in 'field list' in secret_site/public_html/wp-content/plugins/mailpoet/vendor-prefixed/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2 
Stack trace: 
#0 [...]/public_html/wp-content/plugins/mailpoet/vendor-prefixed/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(2):
 PDO->query('SELECT t0.name ...') 
#1 [...]/public_html/wp-content/plugins/mailpoet/vendor-prefixed/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2):
 MailPoetVendor\Doctrine\DBAL\Driver\PDOConnection->query('SELECT t0.name ...') 
#2 [...]/public_html/wp-content/plugins/mailpoet/vendor-prefixed/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(2):
 MailPoetVendor\Doctrine\DBAL\Connection->executeQuery('SELECT t0.name ...', Array, Array) 
#3 [...]/public_html/wp-content/plugins/mailpoet/vendor-prefixed/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 2
```

**To reproduce**
* Activate "Mail Poet 3 (New)" from inside the WP Dashboard
* The exception shows up in the top row of the dashboard.  

**Versions (please complete the following information):**
- WordPress version: 5.5
- PHP version: 7.2
- MailPoet version: 3.49.0

**Comment by fridde** [comment]
By the way: A roll back to 3.48.0 eliminates the problem.

**Comment by costasovo** [comment]
Hi @fridde,
we added the status column in 3.49.0. It seems that migration failed to execute for some reason.
You can try to update to the latest version of the plugin and it will run the migration again.

**Comment by fridde** [comment]
Coming back to this issue: I stayed on 3.48 a while, but I had foolishly activated automatic updates. So now the problem reappeared and persists at any version up to the current.

A weird effect (except for the error notification) of this seems to be that even though I try to reach the edit page of a subscriber, I end up on ?page=mailpoet-subscribers#/new instead.

Any way I can manually migrate?

**Comment by fridde** [comment]
I migrated manually by cross checking recent commits and adding the missing columns directly via SQL commands. 

Quite a pain in the ass, but it solved the issue.
