### ISSUE TITLE
How to remove Help Scout Beacon popover?

### ISSUE THREAD

**Issue by poehaldur** [mailpoet/mailpoet#3044]
My clients don't speak English and they think the blue chat bubble is my support. I cannot use CSS, since it is an iframe. I also could not find the function that adds the chat bubble.

Is there a code snippet into my functions.php that would remove it?

I tried this with css but no luck, the bubble is still there:
function whitelist_ame_admin_color_style($styles) {
  $styles[] = '/admin/admin.css';
  return $styles;
};
add_filter('mailpoet_conflict_resolver_whitelist_style',
'whitelist_ame_admin_color_style');

![download](https://user-images.githubusercontent.com/32192439/92928109-512d4c80-f447-11ea-8012-45b76d6af4fd.png)

**Comment by wxa** [comment]
@poehaldur You can use this snippet: 

```php
add_action('admin_head', 'hide_mailpoet_beacon');
function hide_mailpoet_beacon(){
?>
<script>var hide_mailpoet_beacon = true;</script>
<?php
};
```

**Comment by poehaldur** [comment]
Beautiful, thank you :)
