### ISSUE TITLE
Feature Request: Custom Dynamic Segments.

### ISSUE THREAD

**Issue by deltafactory** [mailpoet/mailpoet#3059]
I would like to request support for extensible dynamic segments. Currently, the dynamic segments include WP Roles and WooCommerce integration in a semi-hardcoded fashion. I have a need to create additional dynamic segments based on user metadata and would love to share the framework established by the underlying classes as opposed to hacking together an alternate interface.

On a related note, it would be great to chain together multiple parameters into a segment such as "WP Roles: Role X and Role Y" instead of creating 2 different segments and addressing them both to a message.

Thank you for your consideration.

**Comment by pavel-mailpoet** [comment]
Hello deltafactory,
we have a dedicated service for the feature requests. Other users can also see and vote for their favourite feature requests (which helps us make decisions). We are a small team and we don't have the capacity to keep tracking feature requests in many different services, therefore we decided to direct all users to https://feedback.mailpoet.com/.
