### ISSUE TITLE
Prevent Mailpoet from being loaded on every web front page load

### ISSUE THREAD

**Issue by ottok** [mailpoet/mailpoet#3133]
I am doing speed optimization to my site.

While running Xdebug against the front page of my site, I noticed it spends about a lot of the PHP execution time in loading Mailpoet.

Tracing it I can see that wp-settings.php of WordPress core loads `plugins/mailpoet/mailpoet.php` which consumes 32 % of the total page load time:

![image](https://user-images.githubusercontent.com/668724/97215782-94f8cd00-17cd-11eb-95c6-973f536b7224.png)

Inside MailPoet the slowest thing is `mailpoet_initializer.php` which loads `MailPoet\DI\ContainerWrapper->get` which in turn loads `MailPoetGenerated\FreeCachedContainer->get`, which loads `MailPoetGenerated\FreeCachedContainer->getInitializerService` which in turn loads this:

![image](https://user-images.githubusercontent.com/668724/97215990-d8533b80-17cd-11eb-967d-aaea42c2cb99.png)

Does MailPoet really have to load this much on every page load? Maybe some point in the code chain could have `is_admin()` and abort if not in WP admin? Is really all this loading always needed for every front page load?

Thanks for a very useful. I hope you find ways to make it also very fast :) 

- WordPress version: 5.5.1
- PHP version: 7.4
- MailPoet version: 3.53.0

**Comment by NeosinneR** [comment]
Hi @ottok, can you please look at the MailPoet settings, if you have Newsletter Task Scheduler set to `Visitors to your website`? 
https://kb.mailpoet.com/article/129-what-is-the-newsletter-task-scheduler

**Comment by ottok** [comment]
Yes, I have:
![image](https://user-images.githubusercontent.com/668724/98792653-7d495780-240f-11eb-8d19-3c15e57eecbe.png)

I assumed this would be using [WordPress Cron API](https://developer.wordpress.org/plugins/cron/), but is it some custom thing instead?

I checked with `wp cron event list` and there are no Mailpoet functions listed.

Also no function calls in code to WP cron:
```
mailpoet$ grep -rF wp_next_scheduled *
mailpoet$ grep -rF wp_schedule_event *
mailpoet$ 
```

Why don't you use WP cron as all other plugins do?

**Comment by NeosinneR** [comment]
@ottok we are not using WP-Cron mostly for reliability issues. With WP-Cron, there is no guarantee that the task will be run at exactly the scheduled time. Another reason is, that WP-Cron is shared between all plugins, and if any other plugin has errors or is stuck on executing some long-lasting task, MailPoet wouldn't be able to continue processing tasks (like sending emails). That's why we have our custom script. 

And another reason why MailPoet is loaded every time - we need to check if we need to show a signup form on the current page.

**Comment by ottok** [comment]
Maybe you could add WP cron as the 4. option? It run reliable everywhere I know. Yes, historically it has had issues but not anymore for years.

Thanks for looking into it and for making a great plugin!

**Comment by NeosinneR** [comment]
Honestly, we don't have any plans to do so, but I can direct you to https://feedback.mailpoet.com/ where you can request this feature, and we might change our minds if more customers would find it useful.
