### ISSUE TITLE
Sending via Sendgrid API not working

### ISSUE THREAD

**Issue by RobertoDonPedro** [mailpoet/mailpoet#3151]
Sendgrid will no longer accept basic authentication with username and password. The only authentication method supported by  Sendgrid are API keys exclusively by December 9th, 2020.

According to Sendgrid Support username "apikey" and the API key as password should work. However, it does not. When I follow the proposed steps, Mailpoet says Incorrect User/Password.

- MailPoet version: 2.14

**Comment by NeosinneR** [comment]
Hi @RobertoDonPedro, we no longer support MailPoet 2. If the Sendgrid Support suggestion doesn't work, then the only thing we can recommend is upgrading to MailPoet 3, which supports Sendgrid API access.

**Comment by RobertoDonPedro** [comment]
Hi @NeosinneR, the problem here is that Mailpoet 3 requires at least WP 5.3 and most customers have not upgraded to this WP release yet and will not until the mentioned date. 
Any chances to get this included into MailPoet 2 (or at least workarounds/codesamples)?

**Comment by NeosinneR** [comment]
@RobertoDonPedro unfortunately, there is zero chance we'll add this to MailPoet 2.

**Comment by NeosinneR** [comment]
@RobertoDonPedro one thing though, what's the WordPress version you are using? If upgrading to WP 5.3 is only a matter of time, you could use an older version of MailPoet 3 which supports your WP version. Let me know and I can send you a link to download the MailPoet 3 for your WP version.

**Comment by RobertoDonPedro** [comment]
@NeosinneR Running different versions, however a link to the github release supporting WP 4.7.11 would be great

**Comment by NeosinneR** [comment]
@RobertoDonPedro https://github.com/mailpoet/mailpoet/releases/tag/3.48.0 should work, just tried it on WordPress 4.7 and PHP 7.0 (it won't work on PHP 5.6). Let me know if you encounter any errors

**Comment by RobertoDonPedro** [comment]
@NeosinneR I installed it now. It says 

> Your website is running on PHP 7.0.12 which MailPoet does not officially support

However, I could send a test email via Sendgrid API. Thx.

**Comment by NeosinneR** [comment]
@RobertoDonPedro yeah, that's fine. That message is shown when we plan to stop supporting that PHP version in near future, but the plugin is still working correctly. When we actually stop supporting a PHP version, the plugin wouldn't work at all.

**Comment by RobertoDonPedro** [comment]
@NeosinneR Unfortunately there are also several WooCommerce compatibilty issues with this version.

> Fatal error: Uncaught Error: Call to undefined function MailPoet\WooCommerce\wc_hex_is_light() in /htdocs/wp-content/plugins/mailpoet/lib/WooCommerce/Helper.php:46

I could fix this by simply adding the WC function code of `wc_hex_is_light` to your Helper.php file

A bigger issue is that it is not possible to add WooCommerce Products with `Title and a short description` or `Title and description`  to a newsletter - simply nothing happens. The only option that works is `Title only`, but this is not sufficient to move forward.

**Comment by RobertoDonPedro** [comment]
@NeosinneR FYI, I fixed it for Mailpoet 2 as follows. Feel free to add it to your V2 code:

        /**
         * Send MailPoet 2 newsletters via Twilio SendGrid Web API v3 endpoints
         * Requires Twilio SendGrid PHP library: https://github.com/sendgrid/sendgrid-php
         * Installation:
         *  - Add this function to file /wp-content/plugins/wysija-newsletters/mailer/class.sendgrid.php
         * -  Call this function from line 55 (inside function 'sendMail' ) as follows
         *      $result = $this->sendgrid_mail($params);
         *      return $result;
         */
        public function sendgrid_mail($params) {

                require_once dirname(__FILE__) . '/sendgrid-php/sendgrid-php.php';

                $email = new \SendGrid\Mail\Mail();
                $email->setFrom($params['from'], $params['fromname']);
                $email->setSubject($params['subject']);
                $email->addTos(array_combine($params['to'],$params['to']));
                $email->addContent("text/plain", $params['text']);
                $email->addContent(
                    "text/html", $params['html']
                );
                $sendgrid = new \SendGrid($params['api_key']);
                try {
                    $response = $sendgrid->send($email);
                    print $response->statusCode() . "\n";
                    print_r($response->headers());
                    print $response->body() . "\n";
                    return true;
                } catch (Exception $e) {
                    echo 'Caught exception: '. $e->getMessage() ."\n";
                    return false;
                }
        }

**Comment by NeosinneR** [comment]
@RobertoDonPedro for the MailPoet 3 version, I hadn't thought of issues with other plugins, in which case, I can't really recommend any specific version for you. But what you can try, is installing [older versions than 3.48.0](https://github.com/mailpoet/mailpoet/releases?after=3.48.0) and I'm confident there will be one, that will be working. 

And thanks for the MailPoet 2 workaround. Although we won't be issuing an update to MailPoet 2, this might help other users who need to use MailPoet 2 version with SendGrid.
