### ISSUE TITLE
woocommerce customers cannot subscribe to List via the API

### ISSUE THREAD

**Issue by tschopo** [mailpoet/mailpoet#3174]
**Describe the bug**
Woocommerce Customers are automatically added by Mailpoet, the status is set to "unsubscribed". Woocommerce customers are not able to subscribe to the newsletter, since they allready exist. I can add them to the list, but I can not change their status via the API. They do not receive an Opt-In email, since they are already in the database.

**To reproduce**
1. Buy something on woocommerce
2. Then try to subscribe to a newsletter
3. Think you are subscribed, but never receive a newsletter, since the status is still "unsubscribed"
4. Do not receive a opt-in email.
5. Be frustrated.

**Actual behavior**
If I want to subscribe a customer to a list via API::subscribeToLists but if the status of the customer is unsubcribed (all woocommerce customers have this status) then the customer is added to the list, but the status is still unsubscribed.

**Expected behavior**
If I call API::subscribeToLists I expect that the status is changed to subscribed OR that a opt-in email is sent.

**Comment by costasovo** [comment]
Thank you for reporting the issue @tschopo. I could replicate it and confirm it is something we should fix as you've suggested.
I've added a ticket into our internal ticketing system. We are quite busy at the moment, and it might take a while to get to it.

**Comment by saroarhossain57** [comment]
Hi @costasovo 
Do you guys allow contributors to open pull requests?

**Comment by alex-mpoet** [comment]
@saroarhossain57 
> Do you guys allow contributors to open pull requests?

Yes. A pull request should follow our [contributing guidelines](https://github.com/mailpoet/mailpoet/blob/trunk/CONTRIBUTING.md).
