### ISSUE TITLE
Accessibility checkboxes and radio buttons

### ISSUE THREAD

**Issue by alekssamos** [mailpoet/mailpoet#3189]
**Describe the bug**
Hi. I am blind and have a problem with the WordPress plugin.
In the settings or in the first wizard.
File: mailpoet-plugin.08bf582b.css
Selector: .mailpoet-form-checkbox input
if set `visibility: hidden;`, I can't find out if the checkbox is checked or not, the same applies to radio buttons, enabled or disabled. You can't focus from the keyboard either.
When i change on `visibility: visible;`,
I can interact using the screen reader well.

**To reproduce**
1. Download, Run and/or install NVDA screanreader https://www.nvaccess.org/download/
2. Go to Wordpress admin
3. Activate first installed plugin (/wp-admin/admin.php?page=mailpoet-welcome-wizard) or go to forms list (/wp-admin/admin.php?page=mailpoet-forms#/)
4. Try focusing on a checkbox or radio button

**Actual behavior**
A clear and concise description of the incorrect behavior.
NVDA will only read the label, but not the state, checked or unchecked
**Expected behavior**
NVDA reads both the label and the state of the element.

**Screenshots**

**Versions (please complete the following information):**
- WordPress version: 5.5.3
- PHP version: 7.4
- MailPoet version: 3.54.2

**Additional context**
If necessary, you can use the WAI-ARIA  standards  and apply special Roles
https://developer.mozilla.org/en/docs/Web/Accessibility/ARIA/Roles

Learn more about the standard:
https://www.w3.org/WAI/standards-guidelines/aria/

**Comment by NeosinneR** [comment]
Hi @alekssamos, thanks for contacting us. We are aware, that the MailPoet is not very accessibility friendly. We do want to change this in the future but given our current priorities and upcoming holidays, it won't be in the very near future. But it is on our roadmap. Thank you also for mentioning the NVDA screen reader, it will definitely help during development. We'll let you know here once this specific issue is fixed.

**Comment by triple0t** [comment]
Hi @alekssamos 

Thank you for opening this issue. 

We have started working on improving the accessibility of the MailPoet plugin, and we are excited to inform you this issue has been fixed and released in MailPoet v3.90.0.

Regards
