### ISSUE TITLE
MailPoet 2 to MailPoet 3

### ISSUE THREAD

**Issue by GermaineMills** [mailpoet/mailpoet#3214]
I was adding 3 to my install and I cannot find the user/lists.

I was supposed to import but didn't get a chance to and was never prompted again. 

PHP version: 7.3.23
MailPoet Free version: 3.55.1
MailPoet Premium version: N/A
MailPoet Premium/MSS key: null
WordPress version: 5.5.3
Database version: 5.6.40-84.0-log
Web server: Apache
Server OS: Linux siteground283.com 3.12.18-clouder0 #3 SMP PREEMPT Thu Sep 10 15:47:13 EEST 2020 x86_64
WP_MEMORY_LIMIT: 768M
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
PHP max_execution_time: 120
PHP memory_limit: 768M
PHP upload_max_filesize: 128M
PHP post_max_size: 128M
WordPress language: en_US
Multisite environment?: No
Current Theme: Divi Child Theme (version 0.0.1)
Active Plugin names: gravityforms/gravityforms.php, bloom/bloom.php, easy-digital-downloads/easy-digital-downloads.php, google-analytics-for-wordpress/googleanalytics.php, mailpoet/mailpoet.php, mainwp-child/mainwp-child.php, monarch/monarch.php, nav-menu-roles/nav-menu-roles.php, sucuri-scanner/sucuri.php, user-role-editor/user-role-editor.php, wordfence/wordfence.php, wordpress-seo-premium/wp-seo-premium.php, wp-security-audit-log/wp-security-audit-log.php, wp-sync-db/wp-sync-db.php
Sending Method: PHPMail
Sending Frequency: 25 emails every 5 minutes
Task Scheduler method: WordPress
Default Reply-To address: null
Bounce Email Address: null
Total number of subscribers: 6
Plugin installed at: 2020-12-02 19:42:01

**Comment by pavel-mailpoet** [comment]
Hello @GermaineMills 
this is not a support forum, please check this page: https://www.mailpoet.com/support
