### ISSUE TITLE
UI issue: Form posting creates awkward reload

### ISSUE THREAD

**Issue by fridde** [mailpoet/mailpoet#3223]
**Describe the bug**
Currently the way the form for the "add new subscribers" page for admins (```admin.php?page=mailpoet-subscribers#/new```) works, a click on "Save" sends away the form fields, *but* empties the form with no indication to the user that the process has worked. Only seconds later, after the ajax-request comes back, does the user get a notification that everything has worked as intended.

This is very confusing and hard to explain to non-technical users.

**To reproduce**
1. Go to wp-admin/admin.php?page=mailpoet-subscribers#/new
2. Fill out the form correctly.
3. Click on "Save"
4. For the effect to be noticable, there should be some small lag between your browser and the server.

**Actual behavior**
The form clears immediatly and no success or error indication is given, thus implying that something is severely wrong and no data has been send. A short moment of panic arises as all previously entered data seems to be lost.

**Expected behavior**
The form fields should NOT clear *before* the ajax request has returned successfully. While waiting the user should clearly see a "just a second..." notification.

**Versions (please complete the following information):**
- WordPress version: 5.6
- PHP version: 7.4
- MailPoet version: 3.56.2
- MailPoet Premium version: 3.56.0

**Comment by fridde** [comment]
I should add that this coincides with another issue of the same kind:

When I open an individual edit-page, for example ```/wp-admin/admin.php?page=mailpoet-subscribers#/edit/99```, the fields are completely empty *until*`the ajax request to ````/wp-admin/admin-ajax.php``` returns. 

On my server, this takes several seconds and on a slow day, it looks like all data has disappeared.

**Comment by wxa** [comment]
@fridde Hello and thank you for reporting! 

Indeed, there is an UI issue with admin form fields being cleared after clicking "Save" (saving still happens). And no indication of loading on add/edit form pages. We have noted this in our internal system and will be working on fixing it. However, since most of the team is currently on Christmas vacation, I cannot promise it will be fixed by the end of this year. 

Please stay tuned, we'll update this issue once any progress is made.

**Comment by lysyjan** [comment]
Hi @fridde ,
your issue is fixed in our latest version.

Thanks again for reporting the issue!

**Comment by fridde** [comment]
I just tested and it works like a charm.
What a great experience to get this quick feedback! Thanks a lot!
