### ISSUE TITLE
Plugin main file

### ISSUE THREAD

**Issue by szepeviktor** [mailpoet/mailpoet#3231]
You may benefit from my ongoing research on main file parts.
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
There is also a sample implementation included.

**Comment by szepeviktor** [comment]
For example the current global `$mailpoetPlugin` variable could be replaced with an OOP [immutable configuration container](https://github.com/szepeviktor/small-project/blob/master/src/Config.php#L20).

**Comment by costasovo** [comment]
@szepeviktor Thanks for your suggestions! Having plugin version etc. available through a config object sounds like a good idea.

**Comment by flakas** [comment]
Hey @szepeviktor, thank you for the suggestion.
We've noted it and will consider it for future improvements.
In the meantime, I'll close the ticket.

Thanks!
