### ISSUE TITLE
MailPoet 3.60.0 Breaks HTML Customization Capability

### ISSUE THREAD

**Issue by Jetxpert** [mailpoet/mailpoet#3330]
We just installed MP 3.60.0. Upon activation, our newsletter custom field (HTML code) broke (i.e., frontend display is now broken).

Click below for details.

**MP 3.59.2 (custom field looks great):** https://prnt.sc/zrjv17
**MP 3.60.0 (custom field html code no longer working):** https://prnt.sc/zrjz7i

MP Premium 3.60.0 does not appear to be affected by MP 3.60.0

To verify the above, we downgraded MP from 3.60.0 to 3.59.2 and the problem was solved.

Please review and fix ASAP. Also, where can we obtain MP Premium 3.59.0? We need to downgrade it temporarily so we can use MP 3.59.2.

**Our Stats:**

WP Version: 5.6.1
PHP Version: 7.4.15
Avada Version: 7.2.1

**Comment by flakas** [comment]
Hello @Jetxpert,

Thanks for the issue report!
Today we released a fix for it (#3332) in the latest [MailPoet 3.60.1](https://github.com/mailpoet/mailpoet/releases/tag/3.60.1) version.

**Comment by Jetxpert** [comment]
**@flakas,**

Thank you. 5-Stars. Excellent response time.

Cheers!
