### ISSUE TITLE
MailPoet 3.60.0 Changelog Needs Correction

### ISSUE THREAD

**Issue by Jetxpert** [mailpoet/mailpoet#3331]
Please correct your changelog for MP 3.60.0. 

Click [here](https://prnt.sc/zrm4ge) for details.

Thank you!

**Comment by flakas** [comment]
Hello @Jetxpert,

Thank you for mentioning this case.
The changelog matches what we wanted to publish and we will not make any further amendments.
I'll close this issue.

**Comment by Jetxpert** [comment]
Hi @flakas,

Respectfully, we disagree with your decision. Your changelog for MP 3.60.0 has TWO duplicate entries and does not list all of the changes you made during this revision.

We stand by our recommendation to update the changelog (if physically possible after release). 

You can keep the issue closed, but we disagree with it. Plus, it contains a syntax error.

Cheers!
