### ISSUE TITLE
Outlook 2016 Rendering Bug in forwarded mail / broken button template

### ISSUE THREAD

**Issue by fhwebcs** [mailpoet/mailpoet#3367]
**Describe the bug**
Create a mail template that includes a button (use template "Simple Text" for example). If that mail is forwarded via Outlook 2016 the button will be displayed twice (and the 2nd button looks broken).

**To reproduce**
1. Go to 'New Mail' and 'Create' newsletter
2. Select Template 'Simple Text' that includes a call-to-action button
3. Send that mail to an Outlook 2016 client
4. Forward the mail via Outlook

**Actual behavior**
Buttons will be displayed twice, whereby the 2nd button looks broken. Both are clickable and working per se.

**Expected behavior**
Only one button should be visible after forwarding the mail via Outlook.

**Screenshots**
Possible to provide that, but shouldn't be necessary.

**Versions (please complete the following information):**
- WordPress version: 5.5.3 (shouldn't matter)
- PHP version: 7.2.34 (shouldn't matter)
- MailPoet version: 3.54.2

**Additional context**
It seems that there is a missing MSO comment switch in the rendering function (>lib >Newsletter >Renderer >Blocks > Button > render). The second button (rendererd via `<a>` tag) in line 39 should to be exluded for MSO clients (via `<!--[if !mso]><!-- --><a class="mailpoet_button"... >...</a><!--<![endif]-->`).

While fixing the issue I've observed that '`<!--[if !mso]><!-- -->`' will be transformed to '`<!--[if !mso]><![endif]-->`' that prohibits the fix from working.

Why it works in first place (first display of the mail): the second `<a>` link is not visible because of the special style attribute `mso-hide:all` - that style gets lost while forwarding the mail.

I'm thinking about providing a pull request next time :). Thank you!

**Comment by costasovo** [comment]
@fhwebcs Thanks for reporting! We will take a look into this. We have a pretty lot on our plates and the change needs to be tested withing various clients so I can't promise a fast fix.

**Comment by fhwebcs** [comment]
I just looked at why `<!--[if !mso]><!-- -->` is transformed to `<!--[if !mso]><![endif]-->`: It seems that `tburry/pquery` doesn't support the _if non-mso_ conditional comments. For a proper solution it should be fixed within `tburry/pquery` itself. For a workaround it may be possible to utilize the wp filter `mailpoet_rendering_post_process` to fix non-mso conditional styles (either by transforming `<!--[if !mso]><![endif]-->` back to  `<!--[if !mso]><!-- -->` or providing some kind of special shortcodes for this use-case).

**Comment by fhwebcs** [comment]
One more note: The _non-mso_ conditional comment (`[if !mso]`) is used for embedding font styles as well (see `StylesHelper.php`).

Therefor the current rendering example that depends on `[if !mso]` is not working:
`<!--[if !mso]><![endif]--><link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700,700i" rel="stylesheet" /><!--<![endif]-->`

**Comment by fhwebcs** [comment]
Hi, any news here? Best Regards!

**Comment by NeosinneR** [comment]
Hey @fhwebcs, we just released the fix in https://github.com/mailpoet/mailpoet/releases/tag/3.67.0
