### ISSUE TITLE
Shortcode subscriber wrong in filter

### ISSUE THREAD

**Issue by stackfuel** [mailpoet/mailpoet#3393]
# Describe the bug

When implementing a shortcode, a link referral shortcode, for newsletters according to the knowledge base article at <https://kb.mailpoet.com/article/160-create-a-custom-shortcode>, the wrong subscriber is passed.

The example in the knowledge base is:

``` php
add_filter('mailpoet_newsletter_shortcode', 'mailpoet_custom_shortcode', 10, 5);

function mailpoet_custom_shortcode($shortcode, $newsletter, $subscriber, $queue, $newsletter_body) {
  // always return the shortcode if it doesn't match your own!
  if ($shortcode !== '[custom:table]') return $shortcode; 
  
  $table =  "<table border=1>";
  $table .= "<thead><tr><th>Fruit Name</th><th>Fruit Color</th></tr></thead>";
  $table .= "<tbody><tr><td>Apple</td><td>Red</td></tr></tbody>";
  $table .= "<tbody><tr><td>Banana</td><td>Yellow</td></tr></tbody>";
  $table .= "</table>";
  
  return $table;
}
```

So the arguments passed in to the shortcode are:

* `$shortcode`
* `$newsletter`
* `$subscriber`
* `$queue`
* `$newsletter_body`

The argument `$subscriber` always refers to the admin user, instead of the actual user, to which an e-mail shall be send.

# To reproduce

1. create a new list
2. create a new user
3. make the newly created user a subscriber to the list
4. create a newsletter as follows

    ```
    Hello,
    
    [link:xxx]
    ```

5. create a shortcode using the example from the knowledge base
6. log the subscriber in the PHP code
7. send the newsletter to the list, in which the newly created user is
8. see the logs of the PHP code
9. see the e-mail account of the user to see, that the e-mail really arrived

# Actual behavior

A wrong subscriber is given as argument to the filter procedure used for implementing the shortcode.

# Expected behavior

The correct subscriber should be given to the filter procedure used for implementing the shortcode.

# Screenshots

(not applicable)

# Versions (please complete the following information):

- WordPress version: `5.6.2`
- PHP version: `7.4.15`
- MailPoet version: free: `3.57.1`, premium: `3.57.0`

# Additional context

I need the correct subscriber in the filter, in order to render a subscriber specific link into the e-mail.

**Comment by pavel-mailpoet** [comment]
Hello @stackfuel ,

Thank you for writing to us.

1) The subscriber in the custom function should be an entity as described in the documentation, so you should call $subscriber->getId(), but there is currently a bug you need to call $subscriber->id. Hopefully, we will fix that sooner.
2) The admin user. That is not a bug, and that is how the system actually works. I tested that myself, and everything was working correctly. So let me explain this to you:
- First, you design a newsletter with a custom shortcode [link:something]
- Then you go to the last step of the designer, and you are about to send the newsletter
- MailPoet creates a template using a server call, and the shortcode is replaced, and the admin user is used for this, that is, the admin user you are seeing in your log.
- Email is then sent to all the subscribers, but nothing is replaced at this moment
- A subscriber clicks a link, they go to the URL, which is then replaced by the custom code you wrote, and at this point, the shortcode function mailpoet_custom_shortcode is called.

I hope I made this clear to you, if you have more questions, please write us back.

Regards
Pavel

**Comment by stackfuel** [comment]
@pavel-mailpoet Thank you for the quick reply.

This matches, what I have observed in the logs. The thing about seeing the logs when going to the last step before sending you described and so on.

What is still unclear to me is, why the argument is named `$subscriber`, if it is not actually the subscriber, but referring to the admin user. That seems confusing. The other thing that is unclear to me is how I can know which user the e-mail will be send to, inside the filter procedure, so that I can send a user adapted link. So far it seems impossible to get the real subscriber, even if by design.

Is this not anything that is intended to be done using the custom shortcode functionality? (Is my approach wrong?)

The following 2 steps make it seem like the filter procedure cannot know the correct subscriber:

> * MailPoet creates a template using a server call, and the shortcode is replaced, and the admin user is used for this, that is, the admin user you are seeing in your log.
> * Email is then sent to all the subscribers, but nothing is replaced at this moment.

**Comment by pavel-mailpoet** [comment]
Hello again @stackfuel 

Sorry I made a mistake and the procedure is actually talking about `[link:something]` shortcode, not `[custom:something]` shortcode you are asking for. 

I just did a test and did log all the subscriber ids for a testing email. And as you can see on my screenshot there were 8 logs:
![Screenshot 2021-03-18 at 12 21 15](https://user-images.githubusercontent.com/29194603/111618600-da518180-87e4-11eb-8f3b-234b3a19b2b6.png)
That is for 7 subscribers and 1 admin user that was used during template generation. I was able to log the email address of the subscriber during my testing using following code:
```
add_filter('mailpoet_newsletter_shortcode', 'mailpoet_custom_shortcode', 10, 5);

function mailpoet_custom_shortcode($shortcode, $newsletter, $subscriber, $queue, $newsletter_body) {
  // always return the shortcode if it doesn't match your own!
  if ($shortcode !== '[custom:table]') return $shortcode;

  $table =  "<table border=1>";
  $table .= "<thead><tr><th>Fruit Name</th><th>Fruit Color</th></tr></thead>";
  $table .= "<tbody><tr><td>Apple</td><td>Red</td></tr></tbody>";
  $table .= "<tbody><tr><td>Banana</td><td>Yellow</td></tr></tbody>";
  $table .= "</table>";

  log($subscriber->getEmail());

  return $table;
}
```

See this [screenshot](https://d.pr/i/hE7jtY).

**Comment by stackfuel** [comment]
@pavel-mailpoet Thank you again for your quick response!

I have now tried the approach using `[custom:something /]` (the slash is needed for parsing shortcode arguments).

Unfortunately I still only ever see the admin user logged, not the real subscribers, even with this approach. I cannot reproduce the behavior or screenshots you demonstrated above. I also tried to add more subscribers (previously had only one) to the Mailpoet list, each having a different e-mail address, but for each of those I see the admin e-mail being logged.

I might be able to provide more code of my implementation, but I'll have to inquire about it first.

Some ideas arose from looking at my mailpoet settings. Does it make a difference, whether the newsletters/e-mails are send with another hoster, or with the Mailpoet service? I am sending them using another hoster. They do arrive, so that I think that hoster is definitely working, but perhaps something inside Mailpoet only works with the Mailpoet sending service?

What other settings, if any, are required for seeing the correct e-mail addresses / correct users given as subscriber argument?

**Comment by pavel-mailpoet** [comment]
> Does it make a difference, whether the newsletters/e-mails are send with another hoster, or with the Mailpoet service?

No, that shouldn't make any difference

**Comment by stackfuel** [comment]
@pavel-mailpoet Do you have any other suggestions on what else we could try or need to make sure of? Anything people often do wrong? Any perhaps too obvious to see obstacles?

The problem still continues to block progress of the associated tasks for us and working on this has become a big time consumer.

**Comment by rodrigoprimo** [comment]
Hi, @stackfuel. Pavel asked me to check this issue and try the custom shortcode. I got the same results that he got and shared in a message above. `$subscribers` point to the user that will receive the e-mail and not to admin (unless in the case where admin is the recipient of the e-mail or when previewing the email logged in as admin). I'm sorry but I'm afraid there is nothing more we can do from our side to help you. As far as we can test, the functionality seems to be working.

**Comment by stackfuel** [comment]
Hi, thank you for your support guys, much appreciated. We were able to reproduce it and it works as you have described. Thanks, a lot.

**Comment by pavel-mailpoet** [comment]
Glad we could help @stackfuel . Would you mind sharing here more details about your solution? What was wrong, and how did you solve it? I think it would be beneficial in case someone also struggles with this.

**Comment by stackfuel** [comment]
Hello! It is not 100% clear, what exactly fixed the problem for us. What we did was to update to the latest minor version and also comment out a lot of error logs. Previously it sometimes happened, that `error_log`ing certain things, PHP would stop logging everything after that log call. I suspect, that this happens under some conditions, when the expression of which the result shall be logged is wrong in some way, for example accessing a non-existent member or something like that. It might have been a general PHP issue, which prevented the logs with the correct e-mail addresses to show up, after a certain point in the logging. Or it might have been the update to the latest minor version that fixed it for us.

Anyway, we also have a better understanding of when what happens in the flow of sending newsletters no, so thank you for explaining that.

We will use the new version and are now making progress on our implementation.

It would be great to also support normal shortcode attributes in the custom shortcodes, but we can work around this and it would belong to another topic than this issue.

**Comment by pavel-mailpoet** [comment]
Thank you for your reply @stackfuel 

> It would be great to also support normal shortcode attributes in the custom shortcodes, but we can work around this and it would belong to another topic than this issue.

I think we already have that. I am not sure if you are talking about the same stuff. Check this Pull Request: https://github.com/mailpoet/mailpoet/pull/3402

**Comment by stackfuel** [comment]
Thanks for that pointer, it seems to exactly what I was talking about.
