### ISSUE TITLE
Fatal error trying to activate plugin

### ISSUE THREAD

**Issue by maxleistner** [mailpoet/mailpoet#3414]
**Describe the bug**
When trying to activate the plugin, wordpress tells me it would generate a FATAL ERROR.

**To reproduce**
1) Search plugin in wordpress plugin repo
2) Install
3) Activate --> error

**Actual behavior**
Fatal error message

**Expected behavior**
no error message :) 

**Screenshots**
![Bildschirmfoto 2021-03-25 um 15 34 48](https://user-images.githubusercontent.com/7567185/112490729-ece92f00-8d7f-11eb-874c-45301194b93c.png)

**Versions (please complete the following information):**
- WordPress version: 5.7
- PHP version: 7.4
- MailPoet version: 3.60.5

**Additional context**

**Comment by maxleistner** [comment]
i already tried to download the plugin manually and uploaded it to the server. Same error.

**Comment by maxleistner** [comment]
Found some more details: 

```
Class 'MailPoet\Tracy\DoctrinePanel\DoctrinePanel' not found
```

![Bildschirmfoto 2021-03-26 um 09 13 03](https://user-images.githubusercontent.com/7567185/112602039-7ac22a00-8e13-11eb-96b6-5de8a7e362e4.png)

**Comment by pavel-mailpoet** [comment]
Hello @maxleistner , 
I can see you are using Tracy on your website. We are aware of this problem and we are fixing it right now. It should be released in one of the next versions.

For now, the only workaround to fix it is trying to find the faulty plugin/theme and keep it temporarily deactivated, or try to remove/disable Tracy if that’s an option. Also, try to disable `WP_DEBUG`

Sorry about the inconvenience.

**Comment by maxleistner** [comment]
Hi @pavel-mailpoet,

thanks for your response. I disabled your Debugger in `plugins/mailpoet/lib/Doctrine/EntityManagerFactory.php`
![Bildschirmfoto 2021-03-26 um 09 48 11](https://user-images.githubusercontent.com/7567185/112606275-78160380-8e18-11eb-838f-b6bbcaf6895a.png)

After that i could activate the plugin, but now i am getting this error: https://kb.mailpoet.com/article/200-solving-database-connection-issues *but* i am not on localhost, instead i am on a public domain. Might this problem be related?

**Comment by pavel-mailpoet** [comment]
Hmm, that error is definitely not related to the problem above. Please make sure you have all the [dependencies](https://kb.mailpoet.com/article/152-minimum-requirements-for-mailpoet-3) installed. Also, `localhost` could be used even on public websites if the database server is running on the same machine.

**Comment by maxleistner** [comment]
> Hmm, that error is definitely not related to the problem above. Please make sure you have all the [dependencies](https://kb.mailpoet.com/article/152-minimum-requirements-for-mailpoet-3) installed. Also, `localhost` could be used even on public websites if the database server is running on the same machine.

All requirements are valid and database url is an external database, not localhost.

**Comment by maxleistner** [comment]
any ideas @pavel-mailpoet ?

**Comment by pavel-mailpoet** [comment]
Sorry, I don't know.

**Comment by maxleistner** [comment]
This is how you handle customer problems? We wanted to switch to mailpoet with about 3000 mail recipients und you just close this issue which is not resolved?! @pavel-mailpoet

**Comment by NeosinneR** [comment]
Hey @maxleistner, as Pavel mentioned, we are aware of this issue and are working on a proper fix, which should be released soon. In case you require support, see our [Support Policy](https://www.mailpoet.com/support-policy/). In many cases, we require admin access to the website, and GitHub is not suited to exchange such information. 

This GitHub is managed by MailPoet developers (not a support team), and because we are a small team, unfortunately, developers can't provide support here except for quick guidance if we think we can help.

**Comment by maxleistner** [comment]
hey @NeosinneR. Thanks for clarification but i am talking about the database error. Who can help me with this?

**Comment by costasovo** [comment]
You can try replacing these lines in Initializer class (https://github.com/mailpoet/mailpoet/blob/master/lib/Config/Initializer.php#L123-L130)
with 
```
return WPNotice::displayError($e->getMessage());
```
This will print out the error message from DB. It may give you some clue why it can't connect.

**Comment by maxleistner** [comment]
Thanks! @costasovo i get the following error now: 
`MailPoet Fehler: An exception occurred in driver: SQLSTATE[42S22] [1054] Unknown column 'ONLY_FULL_GROUP_BY' in 'field list'`

**Comment by NeosinneR** [comment]
As this requires more investigation and also access to the administration of your website, please, [contact our support](https://www.mailpoet.com/support/).
