### ISSUE TITLE
DB_NAME constant doesn't always exist

### ISSUE THREAD

**Issue by GaryJones** [mailpoet/mailpoet#3441]
When [HyperDB](https://codex.wordpress.org/HyperDB) is being used (replaces WPDB class to support multiple databases), the constant `DB_NAME` might not be defined. HyperDB is used by WordPress VIP.

As such, a PHP Warning can be triggered like:

```
07-Apr-2021 04:55:48 UTC] Warning: Use of undefined constant DB_NAME - assumed 'DB_NAME' (this will throw an Error in a future version of PHP) in /chroot/var/www/wp-content/plugins/mailpoet/mailpoet_initializer.php on line 66
```

Under PHP 8, these PHP Warnings will be a PHP Fatal Error.

To stop the fatal errors, check that constants are defined before using them (at least for the `DB_*` ones).

**Comment by pavel-mailpoet** [comment]
Hello @GaryJones, 

Thank you for raising this issue with us. I am trying to understand how HyperDB works, and I am looking into this problem. 

Correct me if I am wrong, but from my understanding, HyperDB can connect to a different database for a different query. I tried to find documentation and find how does it work. Can you help me with a link? 

I am trying to understand what would it mean for us to fix this problem, but at first glance, it doesn't seem to be an easy fix. We are not using WPDB. We are using IdiORM and Doctrine to connect to the database. I am not sure yet how difficult it would be to start supporting HyperDB.

**Comment by GaryJones** [comment]
@pavel-mailpoet Unfortunately I don't know too much about the HyperDB plugin - all I know is that the MailPoet code is assuming a constant exists, when it doesn't, and that will cause fatal errors under PHP 8. A guard clause can easily be added, and whatever that feature is (maybe the whole plugin) may just not work for customers on sites using HyperDB.

**Comment by flakas** [comment]
For anyone else searching for this problem:
After further research, we identified that at the moment MailPoet is not compatible with HyperDB, and should not activate nor function at all.
We are working towards eventual compatibility, but do not expect to support HyperDB in the near term.
