### ISSUE TITLE
Drop “New” from MailPoet Plugin Name (Backend)

### ISSUE THREAD

**Issue by Jetxpert** [mailpoet/mailpoet#3442]
Reference: [MailPoet 3 WordPress Forum](https://wordpress.org/support/topic/drop-new-from-mailpoet-plugin-name-backend/)

Hi there,

We believe the plugins, “**MailPoet 3 (Old)**” and “**MailPoet 3 Premium (Old)**” do not exist.

Based on the above, recommend deleting the term “**(New)**” from your plugin names “**MailPoet 3 (New)**” and “**MailPoet 3 Premium (New)**” as noted [here](https://prnt.sc/10zxq36).

Using “New” implies there’s an old version of MailPoet 3. If you’re thinking of MailPoet 2, well, it stands on its own.

The change is extremely easy to implement. Simply remove the term "(New)" from the following files:

mailpoet.php ([Details](https://prnt.sc/116lbey))
mailpoet-premium.php ([Details](https://prnt.sc/116l9vw))

No biggie, just a recommendation to prevent or eliminate confusion.

Looking forward to your prompt fix!

Cheers!

-------------------------

The reply we received from MailPoet Support on the above was:

> Hi there,
> 
> Thanks for reaching out!
> 
> It’s on our roadmap indeed, we appreciate your feedback.
> 
> Enjoy the rest of your day and stay safe!
>

**Comment by pavel-mailpoet** [comment]
Thank you for reporting this @Jetxpert You're right, but this is not a developers decision. This is more like a management/marketing decision and we developers cannot make this change on our own. So I am going to close this issue here for this reason.

**Comment by Jetxpert** [comment]
@pavel-mailpoet,

Since DevOps cannot take any action until Marketing approves our request, why did you close this topic? 

Instead of closing the topic, can you defer this request to Marketing?

Thank you!

**Comment by flakas** [comment]
@Jetxpert thank you for the suggestion.
At this time we would prefer to keep the naming as is, so I'll keep the issue closed, although in the future we do intend to change it to something closer to what you suggest.
Present naming is intended to eliminate confusion between MailPoet 2 and MailPoet 3.
