### ISSUE TITLE
Problems with unexpected default database port numbers

### ISSUE THREAD

**Issue by HenkBarreveld** [mailpoet/mailpoet#3468]
**Describe the bug**
MailPoet error message:
 "Unable to connect to the database (the database is unable to open a file or folder), the connection is likely not configured correctly. Please read our [link] Knowledge Base article [/link] for steps how to resolve it."

The error is caused by an unexpected default database port number being used.

Examples, see the WordPress support forum, a.o.: 
- "Local" development platform (former "Local by Flywheel", now WP Engine)
- MariaDB database on a Synology NAS

**To reproduce**
- You have a perfectly working WordPress site (without MailPoet). The wp-config.php specifies a constant setting DB_HOST "localhost" or "127.0.0.1". Access to the database is working all right.
- Install MailPoet: doesn't work and the WP Dashboard shows the above error message.
- Instructions in the referenced Knowledge Base article do not help - because they apply to a different situation.

=> Cause: The server uses an unexpected default database port number. It is not specified in DB_HOST, because it is the default, right? WordPress, the installed theme and 20+ plugins do not have a problem with it, but MailPoet cannot work with it, because it assumes that if DB_HOST does not include a port number, it must use 3306.

**Solution**
Do not get the port number from DB_HOST, assuming that you know the default value. Instead, get it from the database server, using the $wpdb class; similar to how you get the user-defined table name prefix.

I tried to do this, using the SQL global variable 'port'. So I replaced line 86 in `/mailpoet/lib/config/Env.php`, saying:
`self::$dbPort = $port ?: 3306;`
by the following:
`self::$dbPort = $wpdb->get_results("SELECT @@port", ARRAY_N)[0][0];`

That works. 

**Disclaimer**
I do not consider myself to be an expert on this subject; of course you guys know your software endlessly much better then I do, and I may very well be overlooking something or this might create problems elsewhere in the software.

Also, you can argue if this is really a bug. However, I thought I should let you know, for your kind consideration. After all, it is in your interest that users have no problems using your software, also if any problems are not your fault.

By the way, I posted this a few days ago on the WordPress support forum ([here](https://wordpress.org/support/topic/no-more-database-port-number-problems/#post-14345859)), but your plugin support person @dromero20 asked me to post this in your public Github repository "so that our developers can take a further look into it".

Have a nice day!
Henk

**Comment by costasovo** [comment]
@HenkBarreveld Thanks for reporting! I think makes sense. Could you please verify what happens when you simply use just `self::$dbPort = $port;` instead of `self::$dbPort = $port ?: 3306;`?

**Comment by HenkBarreveld** [comment]
Hi @costasovo ,

Thank you, that's quick :-)

I just did the test: replaced `self::$dbPort = $port ?: 3306;` by `self::$dbPort = $port;`. 
I did this on Local; setting in wp-config.php: `define("DB_HOST", "127.0.0.1");`. Made the change, restarted Local, started the servers, opened the website front- and backend.

Result: makes no difference, unfortunately. Site works normally; posts and pages are found in the database, for example. However, in the backend, the ominous MailPoet error message is shown and MailPoet does not appear in the dashboard menu.

Just let me know if I can do any other tests; no problem.

**Comment by costasovo** [comment]
Thanks for checking @HenkBarreveld!

 It looks like `mysqli` that is used by $wpdb [reads defaults from PHP config](https://www.php.net/manual/en/mysqli.construct.php) but PDO (used by MailPoet) doesn't. [@@port is s system variable](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_port) so I guess it is a good idea to use it 👍 
 
I have created a ticket in our internal tracking system, and we will most probably implement the change. It will require some testing, though, and we have quite a lot on our hands, so I can't promise we will handle it soon.

**Comment by HenkBarreveld** [comment]
Hi @costasovo,

Very good, thank you.

You write that this may take some time to implement (if more thorough testing does not show any problems), No problem for me, but it may be a good idea to add a "Solution 3" to the MailPoet knowledge base article [Solving Database Connection Issues](https://kb.mailpoet.com/article/200-solving-database-connection-issues). Something like: 

### Solution 3

- Open the file wp-config.php file.
- Find the line `define('DB_HOST', 'localhost');` or `define('DB_HOST', '127.0.0.1');` 
- Replace it with `define('DB_HOST', 'localhost:<port number>');` resp. `define('DB_HOST', '127.0.0.1:<port number>');`, where <port number> is the port number being used by your database server.

**Comment by HenkBarreveld** [comment]
Hi @costasovo 

Another thought, not related...

I am not sure, but could something like this be a solution for another MailPoet problem I just saw on GitHub:[https://github.com/mailpoet/mailpoet/issues/3441]( https://github.com/mailpoet/mailpoet/issues/3441)?

Best regards,
Henk

**Comment by flakas** [comment]
Hello @HenkBarreveld :wave: 

Earlier this week we've released a new [MailPoet 3.62.0 version](https://github.com/mailpoet/mailpoet/releases/tag/3.62.0), which should resolve the issue with default DB port numbers.
Once you upgrade to it - please let us know if any issues persist. Thanks!

For now we'll assume the issue has been fully resolved, so I'll close the ticket.

**Comment by HenkBarreveld** [comment]
Hi @flakas,

I tested this on [Local](https://localwp.com/): 
- checked the server for the database port number it is using: 10004
- database host setting in wp-config.php: simply 'localhost', without specifying a port number
Result: works, no problem!

Thank you, also for this quick handling.
