### ISSUE TITLE
"Opt in" by default in the Order Pay page

### ISSUE THREAD

**Issue by claudiosanches** [mailpoet/mailpoet#3473]
**Describe the bug**
Hello team!

While smoke testing WooCommerce 5.3 RC (but note that this issue applies to any version of WooCommerce) we found an issue with Mailpoet in the Order Pay page, it always present as "opt in" by default, even if you never signed in to the "WooCommerce Customers" list, another part of this bug is that after paying through Order Pay page even if you "opt out" again it will subscribe you to the "WooCommerce Customers" list.

It's possible to access the Order Pay page if for some reason a payment fails, so will be presented a button to go to the ORder Pay page and select another payment method or in the My Account page could be presented with an option to pay for an order with "Pending payment" or "Failed" status.

**To reproduce**
1. Install WooCommerce, while going through the onboard wizard select to install Mailpoet.
2. Create at least one product or import WooCommerce's `sample_products.csv`.
3. Enable "Allow customers to create an account during checkout" in WooCommerce > Settings > Accounts & Privacy. Link: `/wp-admin/admin.php?page=wc-settings&tab=account`
4. Access your shop in a private window and add some products to the cart.
5. Place an order without "opt in" to Mailpoet, make sure to register your user so you can access the "My Account" page later.
6. Access `/wp-admin/admin.php?page=mailpoet-subscribers/` and check that your new user is only subscribed to `WordPress Users` list.
7. Go to `/wp-admin/edit.php?post_type=shop_order`, edit your last order and change its status to "Failed" or "Pending payment"
8. Now back to your new user go to "My Account > Orders" (e.g: `/my-account/orders/`).
9. Click in "Pay" in your last order, it will show you the "Order Pay" page, note that is now "opt in" by default.
10. Uncheck this box again and make a new payment for this order.
11. Finally go back to  `/wp-admin/admin.php?page=mailpoet-subscribers/` and see that your new user now is part of "WooCommerce Customers" list, even without to this list.

**Actual behavior**
The "I would like to receive exclusive emails with discounts and product information (optional)" checkbox is "opt in" by default in the Order Pay page in WooCommerce, while in the checkout is "opt out" by default, also placing an order through the Order Pay page will result in getting subscribed to "WooCommerce Customers" list even if you haven't subscribed.

**Expected behavior**
To Mailpoet be "opt out" by default in all pages in case you haven't opt in before or to not subscribe to any customer list if you didn't allowed.

**Screenshots**

**My Account -> Orders page:**

![Screenshot from 2021-04-26 15-36-11](https://user-images.githubusercontent.com/1264099/116133531-32fa2100-a6a5-11eb-920a-1fd349c94740.png)

**Order Pay form:**

![Screenshot from 2021-04-26 15-35-11](https://user-images.githubusercontent.com/1264099/116133791-879d9c00-a6a5-11eb-82fb-29b50bd21862.png)

**Versions (please complete the following information):**
- WordPress version: 5.7.1
- PHP version: 7.4 and 8.0
- MailPoet version: 3.60.9

**Additional context**

**Comment by pavel-mailpoet** [comment]
Hello @claudiosanches,

thank you for reporting this issue. We did some fixes in this area recently so I re-tested the scenario with the latest version, but the problem persists.
