### ISSUE TITLE
WooCommerce registration newsletter field

### ISSUE THREAD

**Issue by Erehr** [mailpoet/mailpoet#3508]
Related to [https://github.com/mailpoet/mailpoet/issues/2795](https://github.com/mailpoet/mailpoet/issues/2795)

Similar to checkout checkbox that was already replaced with woocommerce_form_field there's another one on registration page that is also hardcoded and could use the same fix. 
lib>Subsription>Registration.php

```
public function extendForm() {
    $label = $this->settings->get(
      'subscribe.on_register.label',
      WPFunctions::get()->__('Yes, please add me to your mailing list.', 'mailpoet')
    );
    print '<p class="registration-form-mailpoet">
      <label for="mailpoet_subscribe_on_register">
        <input
          type="hidden"
          id="mailpoet_subscribe_on_register_active"
          value="1"
          name="mailpoet[subscribe_on_register_active]"
        />
        <input
          type="checkbox"
          id="mailpoet_subscribe_on_register"
          value="1"
          name="mailpoet[subscribe_on_register]"
        />&nbsp;' . esc_attr($label) . '
      </label>
    </p>';
  }
```

**Comment by lysyjan** [comment]
Hello @Erehr,

Thank you for your report. We will look at this issue, and we let you know when we solve it.

**Comment by pavel-mailpoet** [comment]
Hi @Erehr, 
I am looking at this and I am not sure if we can use the function `woocommerce_form_field` here. This field is used on the registration form: https://d.pr/i/XJll07 The WooCommerce plugin doesn't have to be active so the function wouldn't exist. Is there something I am missing here?

**Comment by Erehr** [comment]
Right, forgot that wordpress has it's own login form too. How about adding just a filter to optionally modify it? Then simple is_account_page() check should distinguish if it's core or woocommerce form.

**Comment by flakas** [comment]
Hi @Erehr,

Earlier this week we released MailPoet 3.62.0 that added a filter `mailpoet_register_form_extend` you could use for this purpose, originally added via #3517.
Please let us know if the issue persists, but for the time being, I'll close the issue.
Thanks!

**Comment by Erehr** [comment]
Thanks. Tried the filter and it didn't work. I looked into the code and found that it's not applying changes to the form. Simply changing:
`$this->wp->applyFilters('mailpoet_register_form_extend', $form);`
to
`$form = $this->wp->applyFilters('mailpoet_register_form_extend', $form);`
fixed the problem.

**Comment by lysyjan** [comment]
@Erehr @diegoversiani Thank you for the notification. We will fix it.
