### ISSUE TITLE
Loading Google Fonts effect Page Speed

### ISSUE THREAD

**Issue by ahmedhere** [mailpoet/mailpoet#3534]
Hi,

I don't want to load the Mailpoet fonts on my website. When I created the form I select the option to use theme default fonts. So fonts shouldn't be load. 

<img width="1035" alt="Screenshot 2021-05-26 at 2 09 03 AM" src="https://user-images.githubusercontent.com/40412425/119569032-9fad2c00-bdc7-11eb-8447-71691e07afde.png">

Anyhow. when I try to dequeue the handle in my child theme it didn't work 
```
add_action( 'wp_enqueue_scripts', function() {
    wp_dequeue_style( 'mailpoet_custom_fonts' );
}, 1000 );
```
Please fix this issue asap.

> Add This Feature
1. Create an option in the plugin setting to use plugin fonts or not. 
2. Only load that font which we are going to use not a complete list of Google Fonts.

<img width="1411" alt="Screenshot 2021-05-26 at 2 22 19 AM" src="https://user-images.githubusercontent.com/40412425/119570202-3d552b00-bdc9-11eb-9739-3a59e3fe24cf.png">

**Comment by NeosinneR** [comment]
Hi @ahmedhere, you can disable loading Google Fonts with [a filter](https://kb.mailpoet.com/article/332-how-to-disable-google-fonts).

**Comment by ahmedhere** [comment]
Awesome! Thanks for being quick.

`add_filter('mailpoet_display_custom_fonts', function () {return false;});`
