### ISSUE TITLE
Segmenting based on WC subsciption does not included gifted once

### ISSUE THREAD

**Issue by bsmolyanov** [mailpoet/mailpoet#3538]
The new segmenting based on active WC subscriptions works great but does not consider subscriptions made with the plugin [Gifting for WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions-gifting/)

Any chance to include that as well?

**Comment by NeosinneR** [comment]
Hi @bsmolyanov, I see that you also added this request to [feedback.mailpoet.com](https://feedback.mailpoet.com/feature-requests/p/better-segmentation-options), which I appreciate. I'll close this ticket and will track it on the feedback site. But to give you some information, unfortunately, there are no immediate plans to support the plugin, but we might get back to this in the future.
