### ISSUE TITLE
Order of fields on Manage Subscription

### ISSUE THREAD

**Issue by correctness7** [mailpoet/mailpoet#3546]
HI,

It seems that one year and six months have already passed since this problem and remark. Others have the same problem.
How long should I wait for you? When will it be updated?

https://wordpress.org/support/topic/order-of-fields-on-manage-subscription/

Your remarks in the past.

At the moment it isn’t possible to change the field order, but we are looking at improving this page in the future and will add your suggestion to our internal feedback board.

Past problems.

`I created a custom page for managing subscriptions with [mailpoet_manage_subscription]. It works fine – with one problem: the order or the fields. I have two additional custom fields (Title and Institution), which are listed between the status and the listing of the lists. The order of the fields is:

First name
Last name
Status
Title
Institution
Your lists
Can I change the order of the fields? It would be really cool ….`

Kind Regards,

**Comment by flakas** [comment]
Good day @correctness7 ,

Thank you for reaching out.
Unfortunately, we do not have this feature planned in the next several months, but please do vote on the feature in our [feedback board](https://feedback.mailpoet.com/feature-requests/p/order-of-fields-on-manage-subscription).
We frequently consider community requests when planning further MailPoet developments.

If you are comfortable with code, or would be willing to hire a developer to help you, it may be possible to change the field order via this filter: `mailpoet_manage_subscription_page_form_fields`, however this is not something we officially support.

As there is nothing more we can do today, I will close this issue.
