### ISSUE TITLE
CSS incompatible with Flatsome Theme

### ISSUE THREAD

**Issue by slowaways** [mailpoet/mailpoet#3565]
**Describe the bug**
The CSS of MailPoet for the menu icon is imcompatible with Flatsome menu icon:

**To reproduce**
1. Install Flatsome Theme
2. Install MailPoet
3. Open any MailPoet menu item
4. See the menu icon of Flatsome

**Actual behavior**
The Flatsome icon becomes gigantic, surpassing the size limits.

**Expected behavior**
Does not affect the size of other icons. Define more specific CSS.

**Screenshots**
![image](https://user-images.githubusercontent.com/9668277/122504909-a1869b80-cfd1-11eb-9abf-d64612f7c0b3.png)

CSS:
![image](https://user-images.githubusercontent.com/9668277/122504926-ad725d80-cfd1-11eb-95fa-a71493f4c504.png)

**Versions (please complete the following information):**
- WordPress version: 5.7.2
- PHP version: 7.4.2
- MailPoet version: 3.64.0

**Additional context**

**Comment by costasovo** [comment]
@slowaways. The MailPoet plugin tries to prevent loading other plugins' CSS and JS in MailPoet's admin pages. It looks like Flatsome uses some CSS for the icon and when MailPoet's admin page is opened the CSS was not loaded.
There is a filter (`mailpoet_conflict_resolver_whitelist_style`) that allows modification of the list of allowed sources of CSS files. I guess adding `flatsome` to the list should be enough for fixing the issue.
 https://github.com/mailpoet/mailpoet/blob/8ff41919242d9aecc7a6e452c4ee3aa3566ce825/lib/Util/ConflictResolver.php#L84
