### ISSUE TITLE
CSS of sidebar forms editor (Gutenberg editor)

### ISSUE THREAD

**Issue by slowaways** [mailpoet/mailpoet#3566]
**Describe the bug**
Problem displaying right sidebar when editing block style form.

**To reproduce**
1. Get to MailPoet Menu -> Forms
2. Create a form
4. Select any block style (any long vertical content in the sidebar)
3. See the problem

**Actual behavior**
Horizontal scroll bar should not appear. Missing right padding for vertical scrollbar.

**Expected behavior**
Horizontal scroll bar hidden. Right padding of 17px for vertical scrollbar.

**Screenshots**
The problem:
![image](https://user-images.githubusercontent.com/9668277/122629985-166fd900-d097-11eb-8d06-5a7a47c2bdcb.png)

Expected:
![image](https://user-images.githubusercontent.com/9668277/122629914-9ea1ae80-d096-11eb-8a9b-6e1d0ada7240.png)

**Fixes**
.interface-interface-skeleton__sidebar {
    overflow-x: hidden;
}
.interface-complementary-area {
    width: 285px;
    padding-right: 17px;
}

Source code:
![image](https://user-images.githubusercontent.com/9668277/122630008-31dae400-d097-11eb-8a98-33e5b86e728b.png)

**Versions (please complete the following information):**
- Browser version: Firefox 89.0.1 (64-bit)
- WordPress version: 5.7.2
- PHP version: 7.4.2
- MailPoet version: 3.64.0

**Additional context**

**Comment by costasovo** [comment]
Thank you @slowaways, for reporting the issue. We will take a look into this.

**Comment by JanJakes** [comment]
Fixed by https://github.com/mailpoet/mailpoet/pull/3667.
