### ISSUE TITLE
Support for PostmarkApp and Modify Email Headers

### ISSUE THREAD

**Issue by bhubbard** [mailpoet/mailpoet#3587]
I submitted the feature request via feedback, but are there hooks I can use to modify headers for emails sent via mailpoet? They use headers to support sending via different streams, as well as tag support, and metadata support.

* [Streams](https://postmarkapp.com/support/article/1207-how-to-create-and-send-through-message-streams)
* [Tags](https://postmarkapp.com/developer/user-guide/send-email-with-smtp)
* [Metadata](https://postmarkapp.com/support/article/1125-custom-metadata-faq)

**Comment by costasovo** [comment]
Hi @bhubbard,
Sorry for such a late answer.
Thanks for submitting the feature request! 👍 

Unfortunately, we don't have any filters for headers, and adding them isn't planned, at least for now.
