### ISSUE TITLE
Update subscriber 

### ISSUE THREAD

**Issue by alex-authlab** [mailpoet/mailpoet#3601]
How to update a subscriber data?

**Comment by costasovo** [comment]
Hi @alex-authlab,

you can add update subscribers in plugin admin section MailPoet > Subscribers and after you hover over a subscriber you can click edit link that appears under the subscriber email.

In case you are asking about programatic approach  you can check our [third party API](https://github.com/mailpoet/mailpoet/tree/master/doc).

Please note that this Github repository is not an ideal place for asking support. Please consider asking on plugin forums https://wordpress.org/support/plugin/mailpoet/ where you can get answers from the users community and also from MailPoet support team.

Thank you!

**Comment by pixerize** [comment]
Hello @costasovo,

I am trying to update the existing subscriber's custom fields with API, but I cannot find anywhere in documentation how to do it. 

Example:
1) Let's say I have an application form, the user already became a subscriber in the past. Populating custom field for MailPoet working fine with API.
2) Now user wants to sign up again for a different job, using the same form. 
3) addSubscriber - throws an error: This subscriber already exists.

Goal: 
I need to enable my form to update custom fields, even if he is already an existing subscriber. 

How to overcome this issue, do you have an API call for updating existing users?

Thank you

**Comment by costasovo** [comment]
Hello @pixerize,

I'm afraid that currently it is not possible to update subscriber custom fields data via the official API. It allows only [adding subscribers to lists](https://github.com/mailpoet/mailpoet/blob/master/doc/api_methods/SubscribeToLists.md) or[ removing them from lists](https://github.com/mailpoet/mailpoet/blob/master/doc/api_methods/UnsubscribeFromLists.md).

MailPoet has a short code `[mailpoet_manage_subscription]` that renders for a registered user renders a form that contains also all custom fields.

I hope that helps!

**Comment by pixerize** [comment]
Hi @costasovo,

This shortcode can be helpful in the future, and for updating the custom fields of the subscribers, I have written a custom PHP code.

Thank you for your reply.
