### ISSUE TITLE
[3.66.0] compile:js Module not found 'react-with-direction/dist/constants'

### ISSUE THREAD

**Issue by Cyrille37** [mailpoet/mailpoet#3625]
**Describe the bug**

```
$ ./do compile:js
 [Exec] Running ./node_modules/webpack/bin/webpack.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'react-with-direction/dist/constants' in '/home/cyrille/Code/dev/WP-mailpoet/wordpress/wp-content/plugins/mailpoet/node_modules/react-with-styles/lib'
    at /home/cyrille/Code/dev/WP-mailpoet/wordpress/wp-content/plugins/mailpoet/node_modules/webpack/lib/Compilation.js:925:10
```

**To reproduce**

```
git checkout 3.66.0
./do install
./do compile:js
```

**Versions (please complete the following information):**
- WordPress version: 5.7
- PHP version: 7.3
- MailPoet version: 3.66.0
- npm version: 6.14.12
- node version: 14.16.1

**Comment by NeosinneR** [comment]
Hi @Cyrille37, I'm unable to replicate the issue (in 3.66.0 nor in 3.67.0). Could you please try deleting the `/node_modules` folder, running `npm install` and then `./do compile:js` if that helps? Thanks!

**Comment by JanJakes** [comment]
Closing as there is no more feedback.
