### ISSUE TITLE
Incorrect use of $metas[0] index in individual newsletter processing

### ISSUE THREAD

**Issue by jimyaghi** [mailpoet/mailpoet#3803]
https://github.com/mailpoet/mailpoet/blob/34ef9fcbbf4e6fd681fec15f5736bd1741c315a8/lib/Cron/Workers/SendingQueue/SendingQueue.php#L290

This line includes the meta data for the first subscriber processed in every call to `sendNewsletter()`. Unlike the others arguments, `$metas` is not reset between iterations.

I believe the line can be modified to this:

```
['unsubscribe_url' => $unsubscribeUrls[0], 'meta' => end($metas)]
```

Alternatively, we can reset `$metas` like the remaining  arguments in that condition block like so:

```
 if ($processingMethod === 'individual') {
        $queue = $this->sendNewsletter(
          $queue,
          $preparedSubscribersIds[0],
          $preparedNewsletters[0],
          $preparedSubscribers[0],
          $statistics[0],
          $timer,
          ['unsubscribe_url' => $unsubscribeUrls[0], 'meta' => $metas[0]]
        );
        $preparedNewsletters = [];
        $preparedSubscribers = [];
        $preparedSubscribersIds = [];
        $unsubscribeUrls = [];
        $statistics = [];
$metas = [];
}
```

**Comment by pavel-mailpoet** [comment]
Thank you, @jimyaghi, for reporting it. You are correct. The code is not working correctly. It didn't cause significant issues yet because none of the individual sending methods is using the `meta` values. But we are planning on fixing this anyway.
