### ISSUE TITLE
Admin menu image max-width restriction lacks a MailPoet specific selector

### ISSUE THREAD

**Issue by Misplon** [mailpoet/mailpoet#3916]
The following [commit](https://github.com/mailpoet/mailpoet/commit/4456ff34da6836e09a83c5a019319bd97cef1519) targets all menu items that use an image. The rule in question should ideally make use of one of the available classes or IDs to avoid targeting the admin images of plugins other than MailPoet. 

Thanks

Andrew

**Comment by Misplon** [comment]
Kindly note that the rule in question is not restricted to MailPoet pages. Even if it was though, it isn't ideal to impact other plugin menu items on MailPoet pages.

`.toplevel_page_mailpoet-newsletters` or `#toplevel_page_mailpoet-newsletters` can be used to target the MailPoet menu images.

**Comment by samnajian** [comment]
Thanks for reporting @Misplon, this is addressed in latest changes.

**Comment by Misplon** [comment]
Hi Sam

Super, thanks for attending.

All the best.

Andrew
