### ISSUE TITLE
Add a do_action for Uncanny Automator to hook into when a user submits a form

### ISSUE THREAD

**Issue by saad-siddique** [mailpoet/mailpoet#3940]
MailPoet users have requested that we add a way for them to trigger an action in [Uncanny Automator](https://automatorplugin.com/) when a user submits a form or is added to a list in MailPoet. This do_action will enable us to create triggers such as “A user submits a form” and “A user is added to a list”, which will enable those MailPoet users to run other actions when this happens, improving the user experience with MailPoet on their sites. We already have a few actions for MailPoet users listed [here](https://automatorplugin.com/integration/mailpoet/).

**Comment by brezocordero** [comment]
Hi @saad-siddique !

Thanks for creating the issue and explaining the context.

We are currently working on a hook that should fit your use case.

The hook will have the information about the subscriber, the list to be added to,  and the form that was submitted.

You can see the hook details on the code: https://github.com/mailpoet/mailpoet/pull/3937/files#diff-abc6711feba06b8e110e84a748f3e7ea07dbc5f73a80116889fbbef744458540R123

And you can follow the PR here: https://github.com/mailpoet/mailpoet/pull/3937

**Comment by JanJakes** [comment]
Fixed by https://github.com/mailpoet/mailpoet/pull/3937.
