### ISSUE TITLE
List Unsubscribe header is incorrectly set with PHPMail Method

### ISSUE THREAD

**Issue by jimyaghi** [mailpoet/mailpoet#4059]
The List-Unsubscribe header is missing angle brackets and ends up being corrupted on the other side:

https://github.com/mailpoet/mailpoet/blob/ac2646ce115ffa49d12f69a1f805ade8f42aac31/mailpoet/lib/Mailer/Methods/PHPMail.php#L83

Perhaps it should be like this:

```
$this->mailer->addCustomHeader('List-Unsubscribe', '<' . $extraParams['unsubscribe_url'] . '>'); 
```

**Comment by JanJakes** [comment]
Hi @jimyaghi, thanks for letting us know! This looks like a wrong format indeed. I create a ticket in our internal issue tracker and we'll get it fixed. Once it's ready, we'll close this issue. Thanks again.

**Comment by rodrigoprimo** [comment]
Just documenting here that today we released a new version of MailPoet that includes a fix to this issue.
