### ISSUE TITLE
"Welcome mails" not working for existing users (which got role change)

### ISSUE THREAD

**Issue by scrobbleme** [mailpoet/mailpoet#4082]
Hello,

There is a strange behevaiour of "Welcome mails"

**My configuration**

- I have existing users with "User Role A"
- I have created a new "Welcome Mail"
  - with condition "Send when user with User Role A is registered"
  - (not the problem, but would be nice: a function: send to all existing users)

**Problem**

I tried to trigger the mail for existing users with just changing their role to something else and back:

- Okay: the user got planned for the "Welcome Mail"
- **Problem**: The mail is never send...

**Mailpoet Status**

- shows users for "planned" 
- but doesn't show these mails in the job overview ...

![image](https://user-images.githubusercontent.com/504835/163533117-aba61b51-2afc-42c8-b5e8-cb3118233911.png)
![image](https://user-images.githubusercontent.com/504835/163533207-b8410cf5-1bcd-4b87-8261-b95e3223b6c8.png)

**Comment by pavel-mailpoet** [comment]
Hi @scrobbleme,

We were testing the behaviour you described, however, we couldn't replicate the issue. The welcome email was sent without problems: https://d.pr/i/f1xkP3

Please note that this Github repository is not an ideal place for asking for support. Please consider asking on plugin forums https://wordpress.org/support/plugin/mailpoet/ where you can get answers from the user's community and also from the MailPoet support team.

If you are a paying customer, you could also use our contact form: https://www.mailpoet.com/support/.

Thank you!

**Comment by scrobbleme** [comment]
@pavel-mailpoet Thanks.

Have you tested it with an existing user, where you just switch the role? 

I've this behavior with 2 welcome mails. New users are fine, existing users don't get the mail. It is scheduled but never send.

**Comment by pavel-mailpoet** [comment]
> Have you tested it with an existing user, where you just switch the role?

Yes, that is how I tested it.

**Comment by scrobbleme** [comment]
@pavel-mailpoet I've created a test environment with only WordPress and Mailpoet.

There I have another strange behavior.

Steps I did:

- Install WordPress
- Create user "Test" with role "subscriber"
- Install Mailpoet
- Create Welcome Mail for role "contributor"
- Change role of "Test" to contributor

What happened:

- a new welcome mail is scheduled and should be sent "immediately"
- but never send, the "scheduled send" is regularly increment, but it is never send

No logs, no errors...

![image](https://user-images.githubusercontent.com/504835/164311096-a3564d21-b656-4cb7-8e6e-4070a01ff962.png)
![image](https://user-images.githubusercontent.com/504835/164311150-2d0cdb4c-0223-4f9f-8599-0b945e9b13f2.png)
![image](https://user-images.githubusercontent.com/504835/164311273-16ab03ff-471b-4c5e-9e70-c0958a5671e1.png)

**Comment by pavel-mailpoet** [comment]
@scrobbleme  As I mentioned, please note that this Github repository is not an ideal place for asking for support. Please consider asking on plugin forums https://wordpress.org/support/plugin/mailpoet/ where you can get answers from the user's community and also from the MailPoet support team.

**Comment by scrobbleme** [comment]
@pavel-mailpoet As a follow-up, maybe for others too… 

I've stumbled upon a similar problem over at https://wordpress.org/support/topic/new-user-no-wellcome-email/
(Thanks for the hint)

The **problem** with `existing users`: they were still `unsubscribed `after installing Mailpoet. (New users got subscribed automatically).

I think this is still a problem of Mailpoet, as there was not reporting, no errors, ntohing.

What is the best place to report such improvements? I'd prefer Guthub.

**Improvement**

- Show a message like "The mail can not be sent, while the user is unsubscribed" in the sending status, instead of just rescheduling the mail.


![image](https://user-images.githubusercontent.com/504835/164618202-a2319f17-caa6-4cc0-ab18-b7b7042a7ba8.png)
