### ISSUE TITLE
Woocommerce Customers that are already subscribed to mailpoet get unsubscribed

### ISSUE THREAD

**Issue by rodentooth** [mailpoet/mailpoet#4245]
**Describe the bug**
Woocommerce Customers that are already subscribed to mailpoet get unsubscribed if they do not check the subscribe checkbox at checkout. See https://wordpress.org/support/topic/wc-customer-get-unsubscribed-if-they-dont-check-subscribe/. 

**To reproduce**

Prerequisites: 

- Not logged in to the wordpress site as an user
- subscribed to one or more lists

Reproduce:
1. Put something in basket & proceed to checkout page
2. enter same email address as already in mailpoet
3. leave "subscribe to newsletter" unchecked
4. Complete the purchase

**Actual behavior**
The customer do not want to unsubscribe, yet when they complete their purchase and therefore the email address is known to mailpoet (Because the customer has submitted their email address through the purchase) mailpoet does not check whether this email is subscribed or not, it just generally unsubscribes them globally.

**Expected behavior**
If an email is known and subscribed to mailpoet after a purchase, do not unsubscribe them! They did not click on anything like "Unsubscribe me" and these customers are very valuable!

**Versions (please complete the following information):**

- WordPress version: 6.0
- PHP version: 8.1.8
- MailPoet version: 3.91.0
- WooCommerce version: 6.6.1

**Comment by JanJakes** [comment]
Thanks for the report, @rodentooth! I can confirm this is indeed happening. We're looking into it, we'll keep you updated.

**Comment by rodentooth** [comment]
Any news on this topic?

**Comment by pavel-mailpoet** [comment]
@rodentooth Today, we released the plugin version 4.18.0, which fixes the issue.
