### ISSUE TITLE
Not escaped character in Italian

### ISSUE THREAD

**Issue by smark91** [mailpoet/mailpoet#4370]
**Describe the bug**
Using the Italian language the following error shows up on the console because the Italian language often use the `'` as a character. So either you use double quote for the message or you need to escape the `'` symbol.
```
Uncaught SyntaxError: missing ) after argument list (at (index):21:49)
```
The error is caused by this lines of code (in the second line)
```
  if (typeof MailPoet !== 'undefined') {
    MailPoet.I18n.add('ajaxFailedErrorMessage', 'Si è verificato un errore nell'elaborazione della richiesta, riprova più tardi.')
  } else {
    setTimeout(initMailpoetTranslation, 250);
  }
```

**To reproduce**

1. Set language to Italian
2. Open any page with the Mailpoet widget

**Actual behavior**
An error break the pages

**Expected behavior**
No error should be present

**Screenshots**
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/11672481/190856979-9fd4459d-5080-4f70-a44a-b3ed9ff8bc22.png">

**Versions (please complete the following information):**

- WordPress version: 6.0.2
- PHP version: 7.4.30
- MailPoet version: 3.97.0

**Comment by websupporter** [comment]
Thank you @smark91 for reporting the issue :heart: . We opened a ticket and PR to fix the issue.
