### ISSUE TITLE
Allow to disable JavaScript validation

### ISSUE THREAD

**Issue by krokodok** [mailpoet/mailpoet#4623]
As far as I understand all forms are validated with parsley.js. However I would like to disable the JS validation completely, so that I can have uniform behaviour throughout all the forms on my website. For example I don't like that the form gets the attribute "novalidate", even though all required inputs have the correct HTML5 "required" attributes.

**Comment by websupporter** [comment]
Hi @krokodok,
thank you for your suggestion and sorry for the late feedback. We track feature requests here: https://mailpoet.canny.io/feature-requests

We would appreciate it, if you could add your request there, so we can evaluate the demand for such a feature.

Thank you and all the best!
