### ISSUE TITLE
We have found a bug concerning MailPoet and would like to inform you of it.

### ISSUE THREAD

**Issue by ringo-boy** [mailpoet/mailpoet#4643]
We have found a bug and would like to kindly inform you about it.
The button to add a shortcode in MailPoet does not respond to anything. I am sure this is a glitch. See also the attached file.
We have confirmed this with the following versions

MailPoet 4.4.0
MailPoet Premium 4.4.0
![reporttt](https://user-images.githubusercontent.com/107394472/211728599-d64774ee-9816-4384-9967-227c29af3619.png)

**Comment by lysyjan** [comment]
@ringo-boy Thank you for the report! We are working on the fix.

**Comment by costasovo** [comment]
@ringo-boy Thanks again for reporting the issue! The fix will be included in the next release.
