### ISSUE TITLE
JS conflict when another plugin loads mixpanel script

### ISSUE THREAD

**Issue by engahmeds3ed** [mailpoet/mailpoet#4712]
**Describe the bug**
There are some other plugins that load MixPanel to track some metrics and if that happen, we can see the following error in console

![image](https://user-images.githubusercontent.com/15707971/216355211-fdcb5f18-309f-4d97-953b-8532330af39b.png)

and this is happening because we define MailPoet global variable here:
https://github.com/mailpoet/mailpoet/blob/05202d572f8c6475d3704e7d0df25d9a6dfadc2b/mailpoet/assets/js/src/mailpoet.ts#L83

and before that we call this analytics_event
https://github.com/mailpoet/mailpoet/blob/05202d572f8c6475d3704e7d0df25d9a6dfadc2b/mailpoet/assets/js/src/mailpoet.ts#L8-L9

which calls this function globally:
https://github.com/mailpoet/mailpoet/blob/47e46aeebed11268b4a5ade6b84223a24ca98ea3/mailpoet/assets/js/src/analytics_event.js#L93

So I believe the main problem comes from this condition:
https://github.com/mailpoet/mailpoet/blob/47e46aeebed11268b4a5ade6b84223a24ca98ea3/mailpoet/assets/js/src/analytics_event.js#L82

it should be something like that:
```
if (typeof window.mixpanel === 'object' && typeof window.MailPoet === 'object') {
```

In the code u depended on that your mixpanel script will not be loaded until u define this global variable MailPoet but we need to make sure that this global variable is there before accessing and altering it.

What do u think?
If it's OK, I can create this small PR to fix it.

**To reproduce**

1. Use the following code inside your wordpress
```
function ahmed_add_mixpanel_code() {
	?>
	<!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
			0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
			for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
	</script><!-- end Mixpanel -->
	<?php
}
add_action( 'admin_print_scripts', 'ahmed_add_mixpanel_code' );
```
2. Visit MailPoet settings page
3. Check console, you will see an error and the page will not load at all.

**Actual behavior**
Console error that prevents the settings page from being loaded at all.

**Expected behavior**
Settings page should appear without any error in the console.

**Screenshots**
Added above.

**Versions (please complete the following information):**

- WordPress version: **6.1.1**
- PHP version: PHP **7.4.32** (cli) (built: Sep 29 2022 22:24:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans
    with Zend OPcache v7.4.32, Copyright (c), by Zend Technologies
- MailPoet version: **4.6.0**

**Additional context**

**Comment by costasovo** [comment]
@engahmeds3ed Thank you for reporting the issue, and sorry for the delayed reply!
 
Your proposal works 👍  We can also fix the issue by making sure we call the function after the global MailPoet is defined on the window in mailpoet.ts, which I slightly prefer because we can also get rid of the side-effect of the import.

I went ahead and created a PR https://github.com/mailpoet/mailpoet/pull/4735
