### ISSUE TITLE
RTL-workaround for the plugin

### ISSUE THREAD

**Issue by shalev92** [mailpoet/mailpoet#4741]
Following up this [feature request](https://mailpoet.canny.io/feature-requests/p/rtl-support) I thoght it might be effective to catch up with a fast issue workaround.

Right now the plugin does not allow support it RTL languages, such as Hebrew and Arabic.

As I am aware of the many efforts needed for a full support, there might be a tweak that can be a partial workaround solution. Maybe there's a way to add function in template files (functions.php) and modify the DIV element in email to be styled with "direction: RTL". 

This will give the community a solution that can be helpful.

**Comment by costasovo** [comment]
Hi @shalev92,

Thanks for the idea. Internally we track a list of issues related to RTL support, and we plan to address them. Unfortunately, I can't give you ETA.

As for the potential workaround, I want to share a couple of hints that might be helpful:

For the email content rendered for sending, we have a filter where you get the rendered email HTML as a string, and you can modify it.

The filter is `mailpoet_rendering_post_process`

Here is an example of usage:
```php
add_filter( 'mailpoet_rendering_post_process', 'process_mailpoet_email' );
function process_mailpoet_email( string $email ) {
    // Some regexp magic that adds direction: RTL
    return $email;
}
```
The email HTML contains a lot of inline styles, so there might be more than one place that needs to be altered.

In case you also need to add some CSS in the admin UI, I guess you can use the WP action [admin_head](https://developer.wordpress.org/reference/hooks/admin_head/)

I hope that helps.
