### ISSUE TITLE
Checkout block: Post editor Mailpoet checkbox and label issues

### ISSUE THREAD

**Issue by ralucaStan** [mailpoet/mailpoet#4894]
**Describe the bug**
In the post editor for the Checkout block, the input introduced by Mailpoet has some small issues:
- the label is higher than its checkbox
- the checkbox input is clickable

**To reproduce**
Make sure you have Storefront and the Checkout block

1. In the editor post, go to a page that hast he Checkout block
2. Click on the Mailpoet checkbox
3. Notice the checkbox gets focused, but not selected
4. Notice that the label is not aligned with the input

**Expected behavior**
- The checkbox should not be clickable at all. Just as the Order note checkbox below
- The label should be aligned with the input, just like in the image below. If the text is longer it should go under the first line.
<img width="619" alt="Screenshot 2023-04-28 at 13 27 08" src="https://user-images.githubusercontent.com/1628454/235136676-83d235da-0b42-4e0a-893f-503131554709.png">

**Screenshots**
<img width="1056" alt="Screenshot 2023-04-26 at 16 32 01" src="https://user-images.githubusercontent.com/1628454/235136885-2fd8d672-f3e1-442e-bdcd-e85aea4c1cdf.png">

**Comment by costasovo** [comment]
@ralucaStan , @kellychoffman Thank you both for reporting the issues! I've created a ticket for this in our internal tracking tool. We will look into this and will post updates here.

**Comment by costasovo** [comment]
@ralucaStan After a closer look, I see that we probably can't fulfill the first point "The checkbox should not be clickable at all. Just as the Order note checkbox below". 
The label next to the checkbox is actually a rich-text component that allows a user to edit the label and insert a link to a page with privacy policy info. Having the possibility to insert the link was a highly requested feature. 

I hope that's ok to keep it clickable for the purpose I mentioned.

**Comment by ralucaStan** [comment]
Hey @costasovo, 
my suggestion was that we disable the clickable checkbox only in the post editor. There elements are not interactive. On the site front-end that checkbox should be clickable.

I hope this helps explain the expected result better.

**Comment by costasovo** [comment]
@ralucaStan Sure. We need it clickable on the front end. I'll disable interactions with the checkbox element only in the post editor. But I'll allow interactions with the text next to the checkbox so that the admin can alter it and add the link. In the previous comment, I talked about the text next to the checkbox because the text next to the Order note is not editable. Sorry for not being clear.

**Comment by ralucaStan** [comment]
Sounds great! Thank you for the extra details @costasovo
