### ISSUE TITLE
Subscription confirmation email isn't html-unescaping site:title in the subject field

### ISSUE THREAD

**Issue by jasononeil** [mailpoet/mailpoet#4947]
**Describe the bug**
The template for confirmation emails includes `[site:title]` by default, but this includes HTML encoded characters. My site name is "Jason O'Neil" and when someone tries to subscribe to my site they see an email with the subject "Confirm your subscription to Jason O&#039;Neil".

**To reproduce**

1. Create a wordpress site with "General Settings -> Site Title" including a special character, like "Jason O'Neil" (not the unicode apostrophe).
2. Set up MailPoet with a list and subscription form
3. In "MailPoet -> Settings -> Signup Confirmation -> Open Template Editor" set the subscription to include `[site:title]` (it should already have this by default)
4. Attempt to subscribe a new email address using one of the forms

**Actual behavior**
The email sent to that address should use unicode in the plain text subject. "Confirm your subscription to Jason O&#039;Neil"

Note: `[site: title]` works correctly in the template body

**Expected behavior**
The email sent to that address has HTML encoding in the plain text subject. "Confirm your subscription to Jason O'Neil"

**Screenshots**
<img width="1032" alt="image" src="https://github.com/mailpoet/mailpoet/assets/315158/37975bbe-d747-455b-989f-11c32f2d5e1d">

<img width="738" alt="image" src="https://github.com/mailpoet/mailpoet/assets/315158/7d2f61c4-76d5-4d14-bbd9-38e5ada3c093">

**Versions (please complete the following information):**

- WordPress version: 6.2
- PHP version: 7.4.3
- MailPoet version: 4.11.1

**Comment by alex-mailpoet** [comment]
Thank you for reporting @jasononeil, I have created an issue in our internal bug tracking system so developer could check and fix it. However, I can't give you a time estimate since this issue is low-priority.
