### ISSUE TITLE
Problem with subscribers not recalculating

### ISSUE THREAD

**Issue by ringo-boy** [mailpoet/mailpoet#4968]
I am using version 4.17.1 and am reporting a problem with subscribers clicking "Recalculate Now" but not recalculating.
It does not reset the "Calculated Fat minutes ago" when I click on it. Please look into this.

**Comment by pavel-mailpoet** [comment]
Hey @ringo-boy, please contact [our support](https://www.mailpoet.com/support/) so they can look at the issue and help you resolve it. Thank you.
