### ISSUE TITLE
PHP 8: Deprication notice due to wrong parameter type

### ISSUE THREAD

**Issue by Drivingralle** [mailpoet/mailpoet#4981]
**Describe the bug**

On this file: https://github.com/mailpoet/mailpoet/blob/trunk/mailpoet/lib/Config/Menu.php
The addSubmenuPage method uses `null` instead of an empty String and this causes a Depreciation notice on PHP >= 8.0 

Here is an example notice
![Bildschirmfoto 2023-06-08 um 11 53 40](https://github.com/mailpoet/mailpoet/assets/1727269/a36ab166-8299-480f-8d5d-dc491be2ab20)

**To reproduce**

1. Enable all logging
2. Enable Mailpoet
3. Visit any backend view

**Actual behavior**
An Depreciation notice is given

**Expected behavior**
No notices

**Screenshots**

**Versions (please complete the following information):**

- WordPress version: 6.2.2
- PHP version: 8.1.9
- MailPoet version: 4.18.0 

**Additional context**

**Comment by pavel-mailpoet** [comment]
Thank you @Drivingralle, for finding and fixing this issue. It makes sense to me, and I will merge it later. I am surprised we didn't catch this before.
