### ISSUE TITLE
Multisite subscribers loading all network users rather than just individual sub-site users

### ISSUE THREAD

**Issue by slightlydiff** [mailpoet/mailpoet#5120]
While I realise the plugin doesn't fully support multisite a big improvement would be to get the subscriber sync sorted which seems a simple fix in mailpoet/lib/Segments/WP.php to the function insertSubscribers() as follows:

```
private function insertSubscribers(): array {
    global $wpdb;
    $wpSegment = Segment::getWPSegment();
    if (!$wpSegment) return [];
    if ($wpSegment->deletedAt !== null) {
      $subscriberStatus = SubscriberEntity::STATUS_UNCONFIRMED;
      $deletedAt = 'CURRENT_TIMESTAMP()';
    } else {
      $signupConfirmationEnabled = SettingsController::getInstance()->get('signup_confirmation.enabled');
      $subscriberStatus = $signupConfirmationEnabled ? SubscriberEntity::STATUS_UNCONFIRMED : SubscriberEntity::STATUS_SUBSCRIBED;
      $deletedAt = 'null';
    }
    $subscribersTable = Subscriber::$_table;
	  $blog_id = get_current_blog_id();
	  if ( is_multisite() && $blog_id) {
		  $blog_capabilities = $wpdb->get_blog_prefix( $blog_id ) . 'capabilities';

		  $insertedUserIds = ORM::for_table($wpdb->users)->raw_query(sprintf(
			  'SELECT %2$s.id, %2$s.user_email as email FROM %2$s
    	JOIN %3$s ON %2$s.id=%3$s.user_id
        LEFT JOIN %1$s AS mps ON mps.wp_user_id = %2$s.id
        WHERE %3$s.meta_key="%4$s" AND mps.wp_user_id IS NULL AND %2$s.user_email != ""
      ',
			  $subscribersTable,
			  $wpdb->users,
			  $wpdb->usermeta,
			  $blog_capabilities
		  ))->findArray();

		  Subscriber::rawExecute(sprintf(
			  '
        INSERT IGNORE INTO %1$s(wp_user_id, email, status, created_at, `source`, deleted_at)
        SELECT wu.id, wu.user_email, "%4$s", CURRENT_TIMESTAMP(), "%3$s", %5$s FROM %2$s wu
          JOIN %6$s ON wu.id=%6$s.user_id
          LEFT JOIN %1$s mps ON wu.id = mps.wp_user_id
          WHERE %6$s.meta_key="%7$s" AND mps.wp_user_id IS NULL AND wu.user_email != ""
        ON DUPLICATE KEY UPDATE wp_user_id = wu.id
      ',
			  $subscribersTable,
			  $wpdb->users,
			  Source::WORDPRESS_USER,
			  $subscriberStatus,
			  $deletedAt,
			  $wpdb->usermeta,
			  $blog_capabilities
		  ));
	  } else {
		  $insertedUserIds = ORM::for_table($wpdb->users)->raw_query(sprintf(
			  'SELECT %2$s.id, %2$s.user_email as email FROM %2$s
        LEFT JOIN %1$s AS mps ON mps.wp_user_id = %2$s.id
        WHERE mps.wp_user_id IS NULL AND %2$s.user_email != ""
      ', $subscribersTable, $wpdb->users))->findArray();

		  Subscriber::rawExecute(sprintf(
			  '
        INSERT IGNORE INTO %1$s(wp_user_id, email, status, created_at, `source`, deleted_at)
        SELECT wu.id, wu.user_email, "%4$s", CURRENT_TIMESTAMP(), "%3$s", %5$s FROM %2$s wu
          LEFT JOIN %1$s mps ON wu.id = mps.wp_user_id
          WHERE mps.wp_user_id IS NULL AND wu.user_email != ""
        ON DUPLICATE KEY UPDATE wp_user_id = wu.id
      ',
			  $subscribersTable,
			  $wpdb->users,
			  Source::WORDPRESS_USER,
			  $subscriberStatus,
			  $deletedAt
		  ));
	  }

    return $insertedUserIds;
  }
```
Just fixing this one thing would really help if possible.

**Comment by JanJakes** [comment]
Hi @slightlydiff, thanks for the report. Unfortunately, MailPoet currently doesn't support multisite installations. There are multiple known issues that need to be resolved for multisite support. While these are on our radar, we can't make any promises at the moment. I'm adding your suggestion to our tracking system. In the meantime, feel free to express your preferences via [our feedback form](https://feedback.mailpoet.com/feature-requests). Thanks for understanding.

**Comment by slightlydiff** [comment]
Hi @JanJakes, OK, thanks.  Is there a list of issue on multisite somewhere?  I'd just like to work through them as I need to get it supporting multisite for a number of clients.

**Comment by agencelarsen** [comment]
Hi @slightlydiff and @JanJakes . I guess that we are a bunch of guys willing to dive into the project of making MailPoet folly compatible with multisite. Please consider making available a specific roadmap or details about issues in order to allow us contributing and helping.

**Comment by slightlydiff** [comment]
Hi @agencelarsen. Sounds like it, which is good.  The main issue I came across was the one of restricting sub-site subscribers via WordPress / WooCommerce users to be just those on the sub-site and not those on the whole network which I have crudely resolved in my fix above and seems to be working well on our network.  This affect both the number of subscribers and privacy issues.

But I guess this then brings other privacy issues in terms of how to handle subscribers on sub-sites who are already on the network and needs looking into properly.  I'll do some testing over the next couple of weeks and try to come back with some more useful comments.
