### ISSUE TITLE
Key validation error

### ISSUE THREAD

**Issue by LauraHilliger** [mailpoet/mailpoet#5133]
**Describe the bug**
After the most recent update to the Basic plugin, the verification key says it's valid, but MailPoet sends an error that "Your MailPoet Premium plugin is incompatible with the free MailPoet plugin. Register your key or purchase one nowto update the Premium to the latest version."

However, the key IS valid and there's no update to the Premium plugin available. There's no update button on the plugins page, and trying to update from the WP Dashboard has another error ("Update package not available").

**Actual behavior**
The Premium plugin should still be compatible. 

**Screenshots**
![mailpoet-error](https://github.com/mailpoet/mailpoet/assets/539017/f4ed047c-aaff-4d00-9295-96c5eb77a328)
![mailpoet-error02](https://github.com/mailpoet/mailpoet/assets/539017/e62e1431-5318-460c-aca9-3d3548c1682a)
![mailpoet-error03](https://github.com/mailpoet/mailpoet/assets/539017/bce42f38-1f8d-4e54-8604-8258e380d7de)

**Versions (please complete the following information):**

- WordPress version: 6.3.1
- PHP version: 7.4.10
- MailPoet version: 4.26.0
- MailPoet Premium version 4.23.0

**Additional context**
I am a Legacy account holder (which is probably the problem ;)

**Comment by johnolek** [comment]
Hi @LauraHilliger, sorry to hear that you're having trouble with the premium plugin, and thank you for providing all these details!

From what I can tell, it looks like you may be using an API key for a plan that doesn't include premium. When you verify a key that does have premium, you would see a `MailPoet Premium is active` message:

![image](https://github.com/mailpoet/mailpoet/assets/8656640/b6b7742a-49e8-460a-80b4-bfa501349d24)

I think I found you in our system, and I see two API keys, one for up to 1000 subscribers and another for up to 2000, both legacy plans. If that's correct, the up to 1000 key should include premium, whereas the [up to 2000 plan did not](https://web.archive.org/web/20171124042538/https://account.mailpoet.com/). If you've been trying the update with the 2000 subscriber plan, could you please try it with the 1000 plan instead to see if that works?

Alternatively, you should be able to download the premium plugin zip directly from https://account.mailpoet.com/account if you have a plan that has access to premium.

I hope this helps, but if you're still having trouble I would recommend reaching out to support (https://www.mailpoet.com/support/) as I don't believe this is a bug in the plugin itself, but please let us know if you believe that's incorrect.

And a quick note about compatibility, the free and premium plugins need to have the same minor version to be compatible, so for a 4.26.x version of MailPoet you would need 4.26.0 of MailPoet premium.

**Comment by LauraHilliger** [comment]
Thanks @johnolek, I'm not surprised to see you are correct, the other Legacy key works as you said it would. I'm not sure where the 2K plan came from, but when I click on it it also says premium. In any case, I don't need both, and the 1000 works, so thanks!!
