### ISSUE TITLE
Bug | Plugin Fails to Update | V4.33.0

### ISSUE THREAD

**Issue by Generosus** [mailpoet/mailpoet#5237]
**Describe the bug**
MailPoet Free V4.33.0 fails to update.

**To reproduce**
1. Update plugin via WP Admin page.
2. Refresh WP Admin page.
3. Plugin update notification shows up again. 

**Actual behavior**
MailPoet Free does not update. Also, MailPoet Premium downgrades from 4.32.0 to 4.24.0 when attempting to update MailPoet Free.

**Expected behavior**
Both MailPoet Free and MailPoet Premium should update from V4.32.0 to V4.33.0 with no issues.

**Screenshots**
Check the plugin support forum.
Topic: https://wordpress.org/support/topic/bug-plugin-does-not-update/

**Versions (please complete the following information):**

WP 6.3.2
PHP 8.2.11 or higher

**Additional context**

**Comment by jomplox** [comment]
Same problem here and I can’t use any feature. This bug is causing these two errors for me:

`Invalid API endpoint.`

`You have an older version of the Premium plugin. The features have been disabled in order not to break MailPoet. Please update it in the Plugins page now.`

**Comment by jmzolezzi** [comment]
Same error here at different sites, can't update and even manual upload of latest 4.33, later shows the same version.

**Comment by JanJakes** [comment]
Thanks for letting us know. This has been resolved [shortly after the faulty release](https://wordpress.org/support/topic/bug-plugin-does-not-update/#post-17148992).
