### ISSUE TITLE
Action scheduler/cron error

### ISSUE THREAD

**Issue by WillBrubaker** [mailpoet/mailpoet#5281]
**Describe the bug**

I have been experiencing cron problems targeting Mailpoet for a few days now.
here is an example

mailpoet/cron/daemon-runFailedmailpoet-cronNon-repeating2023-11-08 11:23:10 +0000

action failed via WP Cron: A new entity was found through the relationship 'MailPoet\Entities\ScheduledTaskSubscriberEntity#task' that was not configured to cascade persist operations for entity: MailPoet\Entities\ScheduledTaskEntity@22447. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'MailPoet\Entities\ScheduledTaskEntity#__toString()' to get a clue.

Similar to https://github.com/mailpoet/mailpoet/issues/4451
**To reproduce**

1. Not clear...apparently have emails scheduled.

**Actual behavior**
A clear and concise description of the incorrect behavior.

Error and presumably the email wasn't sent.

**Expected behavior**

Error free email sending.
**Screenshots**

**Versions (please complete the following information):**

- WordPress version: 6.4.1
- PHP version: [e.g: 7.4.2]
- MailPoet version: 4.35.1

**Additional context**

7291841-zen
https://wordpress.org/support/topic/fatal-error-and-scheduler-is-not-creating-for-some-post-2/

**Comment by jmaebe** [comment]
We have the same issue. Whenever we publish a new post that triggers sending out email notifications via MailPoet, the cronjob that does so triggers this error. Mails still seem to be sent though.

WP 6.4.1, MailPoet 4.35.1, PHP 8.1.

We add a single new post every week on Sunday, and the first time we got the error was on 5 November. Mailpoet was updated to MailPoet 4.35.0 on 2 November and updated again to 4.35.1 on 8 November, so it seem be related to the former update.
