### ISSUE TITLE
Minor UI Defect: ampersand character in list description

### ISSUE THREAD

**Issue by mdrovdahl** [mailpoet/mailpoet#5384]
**Describe the bug**
I can place an ampersand character "&" in the list description on the list edit page, but when rendered on the list page it shows the html entity instead of the character. I suspect this represents maybe a wider encoding/decoding issue.

**To reproduce**
* Create a list
* Use an `&` in the list description
* View your list from the lists page
* See the ampersand shown as `&amp;`

**Actual behavior**
`&` saved in a list description renders as `&amp;` on the lists page.

**Expected behavior**
I expect text entered in the list description will render on the lists page the same as entered.

**Screenshots**
<img width="1512" alt="Screenshot 2024-01-16 at 11 24 25 AM" src="https://github.com/mailpoet/mailpoet/assets/474467/cdd33aca-2e60-4943-9ad1-eac969529f14">

<img width="1512" alt="Screenshot 2024-01-16 at 11 24 35 AM" src="https://github.com/mailpoet/mailpoet/assets/474467/bfe46b94-cc9a-4bad-875d-c92d3a1afc37">

**Versions (please complete the following information):**

- WordPress version: latest
- PHP version: any
- MailPoet version: latest

**Additional context**

**Comment by JanJakes** [comment]
Hi @mdrovdahl, thanks for reporting!

This seems to have been introduced in https://github.com/mailpoet/mailpoet/commit/d52dfa215c46e370f875680f1a14db77f97da589. To me, the escaping looks redundant, as React will not render HTML, unless `dangerouslySetInnerHTML` is used. I'll create a ticket for this and we'll check it out.
