### ISSUE TITLE
List status shows as "Subscribed" even when the user is "Unconfirmed"

### ISSUE THREAD

**Issue by puntope** [mailpoet/mailpoet#5441]
**Describe the bug**

When a sub is unconfirmed and we check `$subscriber['subscriptions']` the subscriptions appear as `"subscribed"`

**To reproduce**

- Create some unconfirmed sub
- Call `$this->get_subscriber( $email );`  and verify the list appear as `"subscribed"`

**Actual behavior**
- Create some unconfirmed sub
- Call `$this->get_subscriber( $email );`  and verify the list appear as `"subscribed"`

**Expected behavior**
- Create some unconfirmed sub
- Call `$this->get_subscriber( $email );`  and verify the list appear as `"unsubscribed"`

**Screenshots**

<img width="542" alt="Screenshot 2024-02-19 at 16 00 22" src="https://github.com/mailpoet/mailpoet/assets/5908855/a5587a6c-06d4-4b09-91d8-66d5c1362a32">

**Versions (please complete the following information):**

- WordPress version: 6.4.1
- PHP version: 8.1
- MailPoet version: 4.43.1

**Comment by pavel-mailpoet** [comment]
Hi @puntope, thank you for the report. I am sorry, but I am confused. What is the function `$this->get_subscriber`? I cannot find it in the code. Does it refer to the MailPoet API?

**Comment by puntope** [comment]
> I cannot find it in the code. Does it refer to the MailPoet API?

Yes. It's from the API
