### ISSUE TITLE
Popup cannot be dismissed when clicking outside of it

### ISSUE THREAD

**Issue by power941** [mailpoet/mailpoet#5506]
Hello,

I have created a pop-up utilizing the Mailpoet form; however, I am encountering an issue where if you click outside the pop-up, cannot be dismissed.
![image](https://github.com/mailpoet/mailpoet/assets/79302858/5ee6f6b6-3c32-480f-a634-f23badac7229)

If you press on X yes it's closing, but it should be dissmised also when you click outside of it.

MailPoet Free version: 4.44.1
WordPress version: 6.4.3

Kindly help with issue!

Best Regards
Alex

**Comment by costasovo** [comment]
Hi @power941,

Thank you for the report!

The current behavior is intentional. Some forms might have more fields, and an accidental click outside may close the form, and visitors could see what they filled in. Once the form is gone, it won't open again.
