### ISSUE TITLE
API::updateList() prevents updating a list with same name but different description

### ISSUE THREAD

**Issue by ocean90** [mailpoet/mailpoet#5547]
**Describe the bug**
When using `API::updateList()` for an existing list where you only want to update the description you currently get an exception "This list already exists.".

**To reproduce**

1. Create a new list with `API::addList( [ 'name' => 'a', 'description' => 'foo' ] )`.
2. Try to update the list with `API::updateList( [ 'id' => 1, 'name' => 'a', 'description' => 'foo bar' ] )` where `1` is the ID if the list created in step 1.

**Actual behavior**
The `API::updateList()` calls fails with an exception "This list already exists.". This happens because the ID of the list is not used in https://github.com/mailpoet/mailpoet/blob/50df6c3d4ec465873b83d48937182789bb7011f5/mailpoet/lib/API/MP/v1/Segments.php#L62-L63 and https://github.com/mailpoet/mailpoet/blob/50df6c3d4ec465873b83d48937182789bb7011f5/mailpoet/lib/API/MP/v1/Segments.php#L166

**Expected behavior**
The list gets updated and has the new description.

**Screenshots**

**Versions (please complete the following information):**

- PHP version: 8.2.16
- MailPoet Free version: 4.48.2
- MailPoet Premium version: 4.48.0
- WordPress version: 6.4.4

**Additional context**

Related: #4465

**Comment by lysyjan** [comment]
Hi @ocean90!

Today, we released a new version containing the fix for the issue that you reported.

Best regards

**Comment by ocean90** [comment]
Thank you!
