### ISSUE TITLE
Powerful features but poor page customization

### ISSUE THREAD

**Issue by lennondong** [mailpoet/mailpoet#5591]
It was supposed to be a simple and user-friendly plugin, but it ended up consuming two whole days of my time for configuration. 

Currently, there are still unresolved issues: 
1. Unable to modify the default MailPoet page title. 
2. Several default pages are not centered, but aligned to the left, requiring CSS modifications. 
3. The subscription forms created are disordered when accessed on mobile devices. I want to use the form that I develop,but I can't find the correct way.

It's really hard to understand why developers are not allowed to modify the title.

**Comment by JanJakes** [comment]
Hi @lennondong,

Thank you for reaching out to us. It is not fully clear to me to which parts of the plugin you're referring to. If you're running into issues with the manage subscription page, please [check out this guide](https://kb.mailpoet.com/article/222-customize-your-manage-subscription-page). If you need any more help, please contact [our support](https://www.mailpoet.com/support/) so they can look at the issue and help you resolve it. Thank you.
